### ISSUE TITLE
doesn't serves on http://username.github.io/repository

### ISSUE THREAD

**Issue by VikramTiwari** [gdg-x/hoverboard#1]

**Comment by ozasadnyy** [comment]
@VikramTiwari Yes. For now it doesn't have base URL to add. The solution for now is to add manually `/repository` before resources.

**Comment by VikramTiwari** [comment]
@ozasadnyy But adding /repository disables me form building on it in the local environment.

Tried using absolute path: `../../images/*` to `images/*`

which served the images and other data resources but nothing renders on the page.

**Comment by ozasadnyy** [comment]
@VikramTiwari problem not only in resources but in most cases with router. Look
```
http://gdgnd.github.io/hoverboard/#!/blog
```
[Blog link](http://gdgnd.github.io/hoverboard/#!/blog)
and it's working (for sure without .json files from `data` folder, look into DevTools for 404 errors)

As a result you can view index page if you change [this line](https://github.com/GDGND/hoverboard/blob/master/app/elements/routing.html#L11) to
```
page('/', function() {
            trackPageview('/hoverboard');
            app.route = 'home';
            app.scrollToTop();
        });
```

**Comment by VikramTiwari** [comment]
Ah! Sorry, my bad! Totally forgot to check the router.

Closing this for now, but we will need to include support for project pages as well.

**Comment by ozasadnyy** [comment]
Ideally an site generator will do that stuff
