### ISSUE TITLE
Investigate new github pages

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hoverboard#101]
This new update in github pages is really interesting. Although firebase is super easy and mostly free, github pages can be also another easy option. 

https://github.com/blog/2228-simpler-github-pages-publishing

With the new system, the website can be just a sub folder in `master` branch. If we commit the build folder, that can directly published via github pages.

**Comment by ozasadnyy** [comment]
#44

**Comment by juarezpaf** [comment]
Another reference https://www.youtube.com/watch?v=QLVzozWDYAs

**Comment by ozasadnyy** [comment]
@juarezpaf you are talking about automatic deploy from GitHub to Firebase while @tasomaniac about hosting on GitHub Pages :) But CI would be nice to have as well
