### ISSUE TITLE
Website won't load if you have AdBlock running

### ISSUE THREAD

**Issue by milosmns** [gdg-x/hoverboard#102]
I just went to the website with my ad blocker turned on, and nothing loads (Chrome, Windows 10).

Here is a screenshot: 

http://image.prntscr.com/image/d436ba90429c4e91ad80055423808bb6.png

**Comment by ozasadnyy** [comment]
@milosmns could you open dev tools and send console logs?

**Comment by milosmns** [comment]
Yep, here you go:

http://image.prntscr.com/image/75594eb0bc264a7eab0cde9905c5363e.png

Is that what you needed?

**Comment by MrCsabaToth** [comment]
I'm using `uBlock Origin` too + `Ghostery`. The `EasyPrivacy` filter used by uBlock Origin matches on analytics probably to avoid Google analytics. The same filter matches `hoverboard`'s `analaytics.js` too, which results in `HOVERBOARD.Analytics` not defined and that causes an exception in `HOVERBOARD.Analytics.trackEvent('language', 'select', lang);`, and the page remains blank as a result.

The good news is that I have an extremely simple pull request which fixes this: I rename `analytics.js` to `metrics.js`. PR: https://github.com/gdg-x/hoverboard/pull/105

**Comment by MrCsabaToth** [comment]
This issue is probably not restricted to `uBlock Origin` BTW. Every adblocker which is compatible with AdBlock list formats can be affected if they use such a filter which matches on analytics.js

**Comment by MrCsabaToth** [comment]
@milosmns screenshot is about the same thing, `trackEvent` of `HOVERBOARD.Analytics`

**Comment by ozasadnyy** [comment]
Fixed by @MrCsabaToth  in #105 .

**Comment by milosmns** [comment]
Verified.
