### ISSUE TITLE
android app

### ISSUE THREAD

**Issue by alosdev** [gdg-x/hoverboard#103]
it would be nice to have an android application, that is connected to the same firebase database.

**Comment by ozasadnyy** [comment]
Firebase integration is on our roadmap ;)

**Comment by tasomaniac** [comment]
I think Android app would be another project in our Github right?
Is someone working on it right now?

**Comment by ozasadnyy** [comment]
Yeah, @BruSD working on it.

**Comment by BruSD** [comment]
Coming soon, guys!
I guess we will share the source code after DFUA2016

TNX, @ozasadnyy , for the wake up!

**Comment by BruSD** [comment]
and we work on iOS version to

**Comment by friedger** [comment]
Do we need native apps if this is progressive?

**Comment by ozasadnyy** [comment]
For Hoverboard features no, but there are other ideas which web platform doesn't support yet.
Why not if people have fun of it?!

**Comment by alosdev** [comment]
@friedger definitely we need an application  :)

**Comment by ozasadnyy** [comment]
I am personally against this. In any case, it should be separate project, so I close this issue
