### ISSUE TITLE
uBlock Origin stops site from loading

### ISSUE THREAD

**Issue by cledwyn** [gdg-x/hoverboard#104]
The chrome extension https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

forces the site to not load.  See attached screenshot.

![2016-08-18_17-12-01](https://cloud.githubusercontent.com/assets/223836/17792552/ee3aacee-6566-11e6-8b6a-7ee9fba61535.png)

**Comment by ozasadnyy** [comment]
Duplicate #102
