### ISSUE TITLE
The Team page's layout is weird and team member photos don't seem to load

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#106]
On the demo deployed app too.

**Comment by tasomaniac** [comment]
Can you support your issue with possible logs and screenshots. Thanks.

**Comment by MrCsabaToth** [comment]
I'll later, sorry. Maybe it's just some DNS configuration issue, or browser specific.

**Comment by MrCsabaToth** [comment]
Looks like I can only reproduce it right now with Edge. I swear I saw it with other browser too.
![hoverboard_edge_team0](https://cloud.githubusercontent.com/assets/744949/17844128/f4396a3c-67ea-11e6-82ca-b80bda35db4f.jpg)
![hoverboard_edge_team1](https://cloud.githubusercontent.com/assets/744949/17844133/f9043eac-67ea-11e6-8cb3-14215aa07bb9.jpg)
![hoverboard_edge_team2](https://cloud.githubusercontent.com/assets/744949/17844134/fb2a3470-67ea-11e6-9147-72917628739c.jpg)

**Comment by MrCsabaToth** [comment]
Looks like something is not loading, but I don't see any error in the console logs, I also don't see any 404. Only with Edge right now

**Comment by MrCsabaToth** [comment]
All the other views look good though. That's weird.

**Comment by MrCsabaToth** [comment]
For the vertically squished layout of the top part the culprit is a `margin: 0 auto;` for the `.team-page-0 .details-item.team-page`. Besides that I see a ton of unnecessary `-ms` and `-webkit` prefixed CSS rules. We'd need to revise those, there are tools which can help with such. Edge is WebKit based.

**Comment by MrCsabaToth** [comment]
As for the images, I'm not sure what's the problem yet

**Comment by ozasadnyy** [comment]
@MrCsabaToth It's generated by Polymer-CLI, I can't config autoprefixer there..
Regarding this issue, is it Windows 10?

**Comment by MrCsabaToth** [comment]
@ozasadnyy It's Windows 10. I haven't had time to debug this more yet.

**Comment by sophieH29** [comment]
@MrCsabaToth , you were right on margin 0 auto; there is no need of it there.
you can find PR for fix here https://github.com/gdg-x/hoverboard/pull/116
