### ISSUE TITLE
Add schedule block

### ISSUE THREAD

**Issue by friedger** [gdg-x/hoverboard#11]
Add block that shows the schedule based on sessions and speakers data

**Comment by friedger** [comment]
Basic implementation started here: https://github.com/BruGTUG/DevFest2015/commit/cae80e5fc6d42120ceba36fd28cf1cabff1df8d1

**Comment by ozasadnyy** [comment]
Added in release [v.0.2](https://github.com/gdg-x/hoverboard/releases/tag/v.0.2)
