### ISSUE TITLE
Main header banner image responsiveness

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#112]
I'm trying to use the grey background T-Shirt artwork at https://drive.google.com/drive/folders/0B55wxScz_BJtRXREMTE2VTU1UEk
I needed to make the banner really wide, otherwise the graphics would be cut off on a large screen.
So I have right now https://valleydevfest-620d6.firebaseapp.com/images/backgrounds/home.png
The only problem with that is responsiveness: on a small device format the artwork is not there at all.

I see that it boils down to the `image-overlay-wrapper` CSS style, and maybe some styles above it. They say `@apply(--layout-fit);`. I could use some directions, I'm not familiar enough with the site yet. I'd expect to see `background-size` CSS directives somewhere, and play with `contain` vs. `cover` vs. etc.

I wonder if anyone tried that artwork or had similar problem and the best way to solve it.

**Comment by MrCsabaToth** [comment]
(an off topic thing: down at the location I'm integrating VRView for 360 images of the venue. That works with Firefox and Edge, but not with Chrome. My fork is at https://github.com/gdgfresno/valleydevfest/)

**Comment by ozasadnyy** [comment]
Fixed and replaced the home image with your one (if you don't mind) ;)
