### ISSUE TITLE
Speaker popup is missing visual features when non of the skills are colored

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#119]
I made up some skills when I filled out the speaker.json, and now I have more speakers who doesn't have any colored skill. When that happen most of the modal speaker dialog is white, and it's not obvious where is the close button (top left, it's white on white arrow).
![speaker1](https://cloud.githubusercontent.com/assets/744949/18117104/57aeaea2-6f01-11e6-9f51-376b0c499d96.jpg)
![speaker2](https://cloud.githubusercontent.com/assets/744949/18117106/5a15b276-6f01-11e6-85d2-2a03bc2ad3e6.jpg)

**Comment by MrCsabaToth** [comment]
Maybe I should just properly color all the skills and organize them?

**Comment by ozasadnyy** [comment]
Change tags color [here](https://github.com/gdg-x/hoverboard/blob/master/src/styles/shared-styles.html#L42).
tags converts according to this rule:
`Material Design` -> `material-design`

But I agree that there should be fallback color
