### ISSUE TITLE
Add loading animation on startup

### ISSUE THREAD

**Issue by friedger** [gdg-x/hoverboard#12]
When users are visiting the site nothing happens for a while. 
There should a be a loading animation to indicate that the site while appear soon.

**Comment by ozasadnyy** [comment]
In my opinion, it's better to use critical css. @ebidel approved this approach on [Polymer summit in his presentation](https://youtu.be/Yr84DpNaMfk?t=11m50s)

**Comment by friedger** [comment]
Do you have an example?
Am 27.09.2015 12:14 nachm. schrieb "Oleh Zasadnyy" <notifications@github.com

**Comment by ozasadnyy** [comment]
[Polymer gmail](https://github.com/ebidel/polymer-gmail) is a great example

**Comment by ebidel** [comment]
+1 do it!

**Comment by ozasadnyy** [comment]
No loading animation on startup. Progressive web apps methodology will be used instead.

**Comment by tasomaniac** [comment]
:+1:
