### ISSUE TITLE
Fast first load

### ISSUE THREAD

**Issue by friedger** [gdg-x/hoverboard#120]
The page can takes long to load and should show some loading animation.

**Comment by ozasadnyy** [comment]
No loading animation. According to pwa it should load shell first and then content for it

**Comment by friedger** [comment]
Then the shall should have a logo or so..

Am 31.08.2016 10:20 schrieb "Oleh Zasadnyy" <notifications@github.com>:

**Comment by friedger** [comment]
what about amp-install-serviceworker? https://mobiforge.com/design-development/bootstrapping-progressive-web-apps-with-amp-install-serviceworker

**Comment by ozasadnyy** [comment]
it's slightly another case, but I am going to investigate `amp-image` and other components that can help us.

**Comment by ozasadnyy** [comment]
Done in #235
