### ISSUE TITLE
Feedback on setup

### ISSUE THREAD

**Issue by hvisser** [gdg-x/hoverboard#121]
First of all, I really appreciate all the hard work that goes into this template!
I'm setting up our devfest site based on this, and I find it a bit painful. Hopefully this feedback is useful to you.

Customisation _looks_ easy with `hoverboard.config.json` for example, but I find that there are a lot of places where things like "GDG DevFest Ukraine" is showing, even when you update this config. These texts and content descriptions appear in multiple places, multiple times. Not only in json files but also in element files. This makes it hard to customise this template and to make sure that every file has been updated.

Another example, the analytics key is both in `hoveboard.config.json`, but also in `index.html`. The latter is documented, but might not be obvious. 

The "last year" video for example is also hardcoded, while also present in the config file.

```
 _openVideo: function () {
          HOVERBOARD.Elements.Template.openVideo('GDG DevFest Ukraine 2015', 'DfMnJAzOFng', true);
          HOVERBOARD.Analytics.trackEvent('video', 'watch', 'GDG DevFest Ukraine 2015');
        },
```

Maybe the config is a work in progress, I don't know, I can't really find it on the site. For me, as a developer not that familiar with web development all of this makes it a bit hard to configure the site.

**Comment by ozasadnyy** [comment]
Thanks for the feedback @hvisser . We will fix all mentioned above. Please let me know if you meet another dificulties.

**Comment by friedger** [comment]
I would also like to disable certain elements (like social or videos) on the main page as we do not support that.

**Comment by ozasadnyy** [comment]
@friedger you have to delete blocks and their imports manually https://github.com/gdg-x/hoverboard/blob/master/src/pages/home-page.html
