### ISSUE TITLE
Handling large number of ticket types and other ticket enhancements

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#123]
1. More than 3-4 tickets are squash together into one row, no matter how many
2. Longer side content (example: "Student (early)") flows out of rectangle
3. On-site ticket has only one date

Proposed solutions in an upcoming PR:
1. Setting minimum width prevents squashing together and causes natural wrap
2. Allowing word wrap in side content helps the issue
3. Some templating solves this

**Comment by MrCsabaToth** [comment]
I don't have a counter example, but after the fixes 6 tickets with longer side content look like this: http://valleydevfest.com

**Comment by MrCsabaToth** [comment]
![ticket_lonsside](https://cloud.githubusercontent.com/assets/744949/18154962/e6801e56-6fbd-11e6-9317-4f20d215de4b.jpg)
![tickets_squashed](https://cloud.githubusercontent.com/assets/744949/18154967/ea835f0e-6fbd-11e6-9e4b-9aed6729174f.jpg)

**Comment by MrCsabaToth** [comment]
The squash came only on Edge. The long side IMHO looks better if I let it wrap, although in that case the top/bottom margin is thin

**Comment by MrCsabaToth** [comment]
I was thinking that the whole situation could be reduced to 3 tickets saying that students will get $5 discount of any type of ticket. Also notice that with US dollars the currency is ahead of the amount.

**Comment by ozasadnyy** [comment]
@MrCsabaToth let's add some padding on ticket name.
Dollar sign you can change [here](https://github.com/gdg-x/hoverboard/blob/master/data/hoverboard.config.json#L157)

**Comment by MrCsabaToth** [comment]
Weird. Lately I noticed misalignment regarding both the tickets and the session cards (they weren't same height and other weirdness) on the schedule page. I'm not sure what caused it, maybe I messed up something during merging from upstream?

**Comment by ozasadnyy** [comment]
@MrCsabaToth it should be aligned with flexbox. Please provide screenshots and url with deployed website

**Comment by ozasadnyy** [comment]
Looks good at this time. @MrCsabaToth, let me know if you still experience this issue.
