### ISSUE TITLE
I can't have speakers' page without correlated sessions/schedule

### ISSUE THREAD

**Issue by juarezpaf** [gdg-x/hoverboard#125]
I just cloned **hoverboard**, cleaned the `sessions.json` and `schedule.json` files because I don't have these info yet and I got an error:

<img width="783" alt="hoverboard-error-1" src="https://cloud.githubusercontent.com/assets/21221/18156092/e2ac6c90-6fe9-11e6-8e4a-cc1429d61bf5.png">
<img width="1012" alt="hoverboard-error-2" src="https://cloud.githubusercontent.com/assets/21221/18156093/e2ae9fc4-6fe9-11e6-9b56-a3520f2feac8.png">

What I expect is to have the speakers' page independent from those files.

**Comment by tasomaniac** [comment]
I guess as a workaround you can create a session called "To be announced" and you can use that session with every speaker.

**Comment by ozasadnyy** [comment]
Try to comment ajax call [here](https://github.com/gdg-x/hoverboard/blob/master/src/elements/app-data.html#L9). In any case I will think how to make it more automatically.

**Comment by MrCsabaToth** [comment]
We don't have a session schedule yet so I have a dummy/fake session config to sooth the speaker functionality. Same what @tasomaniac says.

**Comment by juarezpaf** [comment]
@MrCsabaToth Initially I did just like that, but it would be nice to have separated sections.

**Comment by ozasadnyy** [comment]
It's recommended to comment requests in [app-data.html](https://github.com/gdg-x/hoverboard/blob/master/src/elements/app-data.html) instead of just clearing the data files.
```
<template>
    <iron-ajax auto url="[[configSource]]" handle-as="json" last-response="{{app.data}}"></iron-ajax>
    <iron-ajax auto url="[[speakersSource]]" handle-as="json" last-response="{{_speakersRaw}}" on-response="_updateSpeakers"></iron-ajax>
    <!--<iron-ajax auto url="[[sessionsSource]]" handle-as="json" last-response="{{sessions}}"></iron-ajax>-->
    <iron-ajax auto url="[[postsSource]]" handle-as="json" on-response="_reversePosts"></iron-ajax>
    <iron-ajax auto url="[[partnersSource]]" handle-as="json" last-response="{{app.partners}}"></iron-ajax>
    <!--<iron-ajax auto url="[[scheduleSource]]" handle-as="json" last-response="{{_scheduleRaw}}"></iron-ajax>-->
    <iron-ajax auto url="[[teamSource]]" handle-as="json" last-response="{{app.team}}"></iron-ajax>
    <iron-ajax auto url="[[videosSource]]" handle-as="json" last-response="{{app.videos}}"></iron-ajax>
  </template>
```
