### ISSUE TITLE
Caching problems

### ISSUE THREAD

**Issue by pflammertsma** [gdg-x/hoverboard#126]
Whenever I deploy a new version onto our Firebase staging host, I have to manually clear the cache with a hard refresh (using Ctrl+F5 in Chrome for Linux).

I had expected that the cache would invalidate and the fresh version would load up the next time, but I've understood that due to offline availability of the site, a popup should instead appear at the bottom of the screen. I haven't seen this popup; what can I do to troubleshoot this?

**Comment by ozasadnyy** [comment]
We are investigating it right now. Thanks for reporting.

**Comment by miketraverso** [comment]
This is something that's repeatable on other WebKit browsers like Safari. Our site will get updated but especially on mobile there's no way to refresh to pull down the updates unless you clear your browser cache.

**Comment by MrCsabaToth** [comment]
I experienced that with PWAs in general, not just hoverboard. Maybe some cache fine tuning could help? At the same time not so long ago I saw really nice "New version available" banner with Chrome.

**Comment by sophieH29** [comment]
this PR https://github.com/gdg-x/hoverboard/pull/136 should fix the problem
