### ISSUE TITLE
Filter is only working on Google Chrome

### ISSUE THREAD

**Issue by juarezpaf** [gdg-x/hoverboard#127]
We received a bug report saying the Filter on Schedule page is not working.
I tested on Safari, Firefox and Edge.
![screen shot 2016-09-08 at 12 05 58 pm](https://cloud.githubusercontent.com/assets/21221/18354642/b676e47e-75bc-11e6-8eee-5b862547d3df.png)

**Comment by juarezpaf** [comment]
@ozasadnyy any updates here? ^_^

**Comment by ozasadnyy** [comment]
@juarezpaf on my list. Probably I will look to it today.

**Comment by ozasadnyy** [comment]
Fixed in develop branch. 
Will be merged into master next week with other fixes.
