### ISSUE TITLE
After deploying Hoverboard - Firebase web app is blank

### ISSUE THREAD

**Issue by cliveb** [gdg-x/hoverboard#129]
Hi Guys, 
Deploying Hoverboard GDG[x] for devfest: my Firebase web app is blank. Chrome devtools shows 'Uncaught SytaxError: Unexpected  token < util.js " error repeats for each js project file.  Anyone else have this error or have any ideas how to debug?  [devfest16-9fbd6.firebaseapp.com/](url)

Last year I tried to use Zepplin for GDG Seattle DevFest. This year we're determined to use Hoverboard, because it is so inspirational:  Firebase + Polymer + Service Worker. However, I am no web pro, more a Golang hacker and stumped (do I have an illegal character in my JS...I pasted the error into google...)

Any tips / directions how to debug appreciated.  
 
THX
Clive @seattlegdg

**Comment by twhetzel** [comment]
I'm gearing up to use this year's Hoverboard. Which version did you pull?

Trish

**Comment by cliveb** [comment]
I pulled latest from master. **https://github.com/gdg-x/hoverboard**

Maybe I should go back and pull a version https://github.com/gdg-x/hoverboard/releases/tag/v.1.0.2

**Comment by MrCsabaToth** [comment]
@cliveb Did the site build (`polymer build`) fine? Did it look good with local `polymer serve`? How did you deploy exactly?

**Comment by cliveb** [comment]
After polymer serve ![polymer serve](https://cloud.githubusercontent.com/assets/733870/18464125/df936e42-7943-11e6-92a0-236602fb9e22.png)

I deployed with Firebase deploy after copying the Firebase console snippet into index.html Add Firebase to your web app
Copy and paste the snippet below at the bottom of your HTML or before other script tags.
<script src="https://www.gstatic.com/firebasejs/3.3.2/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "blah blah long key ",
    authDomain: "devfest16-9fbd6.firebaseapp.com",
    databaseURL: "https://devfest16-9fbd6.firebaseio.com",
    storageBucket: "devfest16-9fbd6.appspot.com",
  };
  firebase.initializeApp(config);
</script>

Firebase engineer had me copy index.html from hoverboard folder to hoverboard/public (Firebase expects index.html here. I don't why my directory tree is messed up.

**Comment by cliveb** [comment]
@twhetzel solved my issue by sharing her screen shot. Key is **build/bundled**. Sharing my screen shot for other newbies like me (screen shots clarify). 
![firebase deployment](https://cloud.githubusercontent.com/assets/733870/18465691/d82bdc80-794c-11e6-9f30-06113e2111aa.png)
