### ISSUE TITLE
Only initial Ukraine builds works [super urgent]

### ISSUE THREAD

**Issue by cliveb** [gdg-x/hoverboard#133]
Using Polymer 0.12.0 

Make changes to data/hoverboard.config.json + index.html for Seattle GDG

Run $ polymer build

Get polymer warning messages screen shot

![polymer build](https://cloud.githubusercontent.com/assets/733870/18533094/673a7e2e-7a95-11e6-9d88-9d1b84603936.png)
 
firebase deploy 

Result same as original Ukraine form git fork repo

Any ideas?  

My repo https://github.com/GDGSeattle/hoverboard

**Comment by cliveb** [comment]
Polymer build wiped out contents of the contents of firebase.json

How do I fix this please?

**Comment by cliveb** [comment]
Using [sudo] install. No errors 
npm 3.10.7
node 6.5.0
bower 1.7.9
polymer 0.12.0 

Reexecuted npm, node, bower, power installs after executing npm clean detailed here https://github.com/Polymer/polymer-cli/issues/220#issuecomment-222292622

**Comment by cliveb** [comment]
Clivebs-bigMac:hoverboard seebe$ bower install
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/seebe/.config/configstore/bower-github.json'
You don't have access to this file.

Fixed it with
[https://github.com/bower/bower/issues/2262#issuecomment-212601652](url)

**Comment by cliveb** [comment]
4 files changed between Hoverboard v. 1.0.2 and my local machine

![4 changes](https://cloud.githubusercontent.com/assets/733870/18539672/f3d1a2da-7acd-11e6-8f1c-949b81644916.png)

**Comment by ozasadnyy** [comment]
@cliveb you have not valid hoverboard.config.json. Please remove a comma [here](https://github.com/GDGSeattle/hoverboard/blob/8ea9707c0aa74c9216a7fb3bd476ef5713c80f44/data/hoverboard.config.json#L209)
Warning is ok during a build :)

**Comment by cliveb** [comment]
@ozasadnyy Resolved build. Thank you.
