### ISSUE TITLE
Sign-in is broken on the deployed master

### ISSUE THREAD

**Issue by cortinico** [gdg-x/hoverboard#1335]
**Describe the bug**
Seems like the deployed version of hoverboard from master has the login feature broken.
When clicking on "Sign In with Google" the following error gets printed on console:

```
"{"error":{"code":403,"message":"Requests from referer https://hoverboard-master.web.app are blocked.","errors":[{"message":"Requests from referer https://hoverboard-master.web.app are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED"}}"
```

We had the same issue on our instance of hoverboard. The problems seems to be related to restrictions of the API key used by hoverboard: 
https://stackoverflow.com/questions/52970822/firebase-auth-internal-error-signup-are-blocked-on-web

Specifically the API key needs to have `Identity Toolkit API` whitelisted.

**To Reproduce**

1. Go to https://hoverboard-master.web.app/
2. Click on "Sign In" button on top right
3. Click on "Sign In with Google"
4. A dialog opens for some seconds and disappears.

**Expected behavior**
You should be able to login to hoverboard correctly.

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome
- Version: 85.0.4183.102

**Comment by abraham** [comment]
It turns out that the `development.json` config was always the default.
