### ISSUE TITLE
Configure Hoverboard for Seattle GDG (or another GDG)?

### ISSUE THREAD

**Issue by cliveb** [gdg-x/hoverboard#134]
Docs / tutorial says to Configure 
https://github.com/GDGSeattle/hoverboard/blob/master/docs/tutorials/configure-app.md

Mainly the following

Most important data/hoverboard.config.json
SEO index.html
GA tracking code in index.html

finally change: Pages config

does instruction mean change all the following files? 

clivebs-bigMac:hoverboard seebe$ grep -rl --exclude-dir='./build/*' 'Ukraine' .
./.git/objects/pack/pack-2ba385472b798ac4dfbb27d64139054e82164f5f.pack
./bower_components/app-layout/demo/contacts.json
./data/blog.json
./data/en/resources.json
./data/posts/2015-10-24-devfest-ua-summary.markdown
./data/posts/2016-05-04-devfest-2016-announced.markdown
./data/posts/2016-05-06-c4p-time.markdown
./data/sessions.json
./data/speakers.json
./data/tweets.json
./data/uk/resources.json
./docs/tutorials/configure-app.md
./images/people/jana_moudra.jpg
./manifest.json
./README.md
./src/elements/header-content.html
./src/elements/social-post.html

**Comment by ozasadnyy** [comment]
No, everything else is up to you.
BUT:
```
./data/blog.json
./data/en/resources.json
./data/posts/2015-10-24-devfest-ua-summary.markdown
./data/posts/2016-05-04-devfest-2016-announced.markdown
./data/posts/2016-05-06-c4p-time.markdown
./data/sessions.json
./data/speakers.json
./data/tweets.json
./data/uk/resources.json
./manifest.json
./src/elements/header-content.html
```
have specific to Ukraine data.
