### ISSUE TITLE
Notifications are broken on the deployed master

### ISSUE THREAD

**Issue by cortinico** [gdg-x/hoverboard#1343]
**Describe the bug**
Seems like the deployed version of hoverboard from master has the notifications feature broken.
When clicking on the bell icon in the top right, the following error gets printed on console:

```
VM58:1 POST https://firebaseinstallations.googleapis.com/v1/projects/hoverboard-master/installations 403
FirebaseError: Installations: Create Installation request failed with error "403 PERMISSION_DENIED: Requests from referer <empty> are blocked." (installations/request-failed).
    at https://hoverboard-master.web.app/node_assets/firebase/firebase-messaging.js?__WB_REVISION__=9af97001ad84db67dae884e85e888007:1:8733
    at https://hoverboard-master.web.app/node_assets/firebase/firebase-messaging.js?__WB_REVISION__=9af97001ad84db67dae884e85e888007:1:1982
    at Object.next (https://hoverboard-master.web.app/node_assets/firebase/firebase-messaging.js?__WB_REVISION__=9af97001ad84db67dae884e85e888007:1:2087)
    at r (https://hoverboard-master.web.app/node_assets/firebase/firebase-messaging.js?__WB_REVISION__=9af97001ad84db67dae884e85e888007:1:833)
```

I've tried to briefly investigate but I wasn't able to find any lead. The issue seems to be related to the messaging initialisation we do in the SW not setting the proper `Referer` header.

https://github.com/gdg-x/hoverboard/blob/3e25c9bd0e523075e88035195650387065850fb9/firebase-messaging-sw.js#L4-L13

A workaround is to remove restrictions on the API key that I would like to avoid.

**To Reproduce**

1. Go to https://hoverboard-master.web.app/
2. Click on the bell icon on the top right
3. Press `Enable` on the Popup
4. The bell icon will be disabled and clickin on it will mention `We can't send you notifications right now. Please enable notifications in your browser`

**Expected behavior**
You should be able to enable notifications from hoverboard correctly.

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome
- Version: 85.0.4183.102

**Comment by abraham** [comment]
The API keys were incorrect. I've updated them and the error has gone away. I'm not convinced notifications are actually working right now though so I need to look at it further.

**Comment by abraham** [comment]
Scratch that. The API Key in the firebase console didn't have any referrer restrictions applied to it.

My best guess at an approach to fix this is have the Firebase browser key not be referrer restricted but be API restricted to a limited number of API. There could then be a second API key that is referrer restricted that has access to more APIs like Maps.

**Comment by cortinico** [comment]
> My best guess at an approach to fix this is have the Firebase browser key not be referrer restricted but be API restricted to a limited number of API. There could then be a second API key that is referrer restricted that has access to more APIs like Maps.

Yup but still not idea.
Interestingly, the console error while running the app locally is:

```
FirebaseError: Installations: Create Installation request failed with error "403 PERMISSION_DENIED: Requests from referer http://localhost:5000/ are blocked." (installations/request-failed).
...
``` 

Is something lost when the app gets deployed?

**Comment by abraham** [comment]
Notifications have been updated and are working currently.
