### ISSUE TITLE
Reloading on firebase hosted site fails

### ISSUE THREAD

**Issue by friedger** [gdg-x/hoverboard#137]
The first time it loads fine, on refresh the site is orange (devfest-belgium.firebaseapp.com)

`app-data:17 Uncaught TypeError: Cannot read property 'reverse' of null_reversePosts 
@ app-data:17s 
@ polymer:5fire 
@ polymer:5_handleResponse 
@ iron-ajax:6

app-data:17 Uncaught TypeError: Cannot set property 'tags' of null_generateSchedule 
@ app-data:17_complexObserverEffect 
@ polymer:5_effectEffects 
@ polymer:5_propertySetter 
@ polymer:5s 
@ polymer:5(anonymous function) 
@ polymer:5_notifyListener 
@ polymer:6(anonymous function) 
@ polymer:5fire 
@ polymer:5_notifyChange 
@ polymer:5_notifyEffect 
@ polymer:5_effectEffects 
@ polymer:5_propertySetter 
@ polymer:5s 
@ polymer:5_handleResponse 
@ iron-ajax:6`

**Comment by ozasadnyy** [comment]
I have refreshed several times, works fine for me. Could you give me more details?

**Comment by friedger** [comment]
maybe just firebase caching old values. Works for me as well :-)
