### ISSUE TITLE
Featured videos section doesn't seem to work

### ISSUE THREAD

**Issue by zptoth** [gdg-x/hoverboard#1410]
**Describe the bug**

Featured videos section doesn't seem to work. Not even on the linked live demo site.

**To Reproduce**

If you click any of the featured videos an invisible popup window is opened, that does not display anything, not even a frame, but the closing (X) sign only in the top left.
The window could be closed by clicking the (X) sign.

**Expected behavior**
The popup window should display the video referenced in **default-firebase-data.json**
I have double-checked and the videos referenced in the demo site have the same youtube id that are referenced from the json file. eg https://www.youtube.com/watch?v=hUY8jg9-ieE
Also tested by replacing sample videos with other ones. Same result.

**Screenshots**
https://drive.google.com/file/d/1dkvYHNQyFCP7iW_ghacB00-qXnFfMdWv/view?usp=sharing

**Desktop (please complete the following information):**

- OS: Debian 10
- Browser: Chrome, Firefox, Opera

The issue seems to be independent from browser or os.

**Smartphone (please complete the following information):**

- Device: OnePlus 7T Pro McLaren
- OS: OxygenOS 10
- Browser: Chrome

The issue seems to be independent from browser or os.

**Comment by abraham** [comment]
I do remember that working at one point but having kind of a weird user experience. Maybe it should play in the carousel or directly open a new tab.

**Comment by zptoth** [comment]
This pop-up window approach could work fine.
This example is not so terrible in my opinion: https://cloud.withgoogle.com/next/sf/sessions#industry-insights

**Comment by abraham** [comment]
Seems potentially related to https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by zptoth** [comment]
Well, autoplay is not too important for me, so if the window could just pop up with the content in it that would be fine.
Right now not even the content could be seen.

**Comment by abraham** [comment]
Digging into it a bit more I'm not sure it is auto-play. The [`<google-youtube-api>`](https://github.com/GoogleWebComponents/google-youtube/blob/master/google-youtube.js#L89) element doesn't seem to be working even though both `dom-if` values wrapping it are true.

**Comment by abraham** [comment]
Have a look at the preview from https://github.com/gdg-x/hoverboard/pull/1426
