### ISSUE TITLE
Small schedule cards don't display multiple tags well

### ISSUE THREAD

**Issue by abraham** [gdg-x/hoverboard#1411]
The tags should probably drop below the length and have more space when they wrap around.

<img width="423" alt="Screen Shot 2020-10-11 at 16 24 42" src="https://user-images.githubusercontent.com/3341/95690569-603a2280-0bde-11eb-976a-fc463493de46.png">

**Comment by giulianovarriale** [comment]
Can I work on this one?

**Comment by abraham** [comment]
Please do!

**Comment by akshitarora921** [comment]
@abraham can I take this?

**Comment by abraham** [comment]
Yes :)

**Comment by akshitarora921** [comment]
Hi @abraham, Can you please give a little bit of an overview? These are the tags attribute of a session right. 
Also, I am getting this error while running this command `npm run firestore:init`
![Screenshot from 2021-11-06 14-53-06](https://user-images.githubusercontent.com/11087313/140604831-b664c806-0a7a-4c74-a53c-2df2bc48f504.png)

**Comment by abraham** [comment]
Yes, tags on a session. If you scroll down https://hoverboard-master.web.app/schedule/ until you find "Intro to TensorFlow" you'll see the issue.

You should be able to run hoverboard locally without changing the configuration and it should read the data from the site I linked to.

The tags are rendered in the [`session-element` component](https://github.com/gdg-x/hoverboard/blob/452240ef7bbc6c939b040b16db442ee8cae80b01/src/elements/session-element.ts#L192-L207).

**Comment by akshitarora921** [comment]
Hi @abraham,
I did a fresh install and just did `npm install` and 'npm start`. I am getting only one tag as 'Cloud' for Intro to TensorFlow.
![Untitled](https://user-images.githubusercontent.com/11087313/140732430-29e921f8-6e75-4603-9af9-33f4255f83b0.png)

**Comment by abraham** [comment]
Try it now. I updated the database for https://hoverboard-dev.web.app/schedule/

**Comment by akshitarora921** [comment]
@abraham thanks, The data is updated now.
