### ISSUE TITLE
the toolbar does not hide in mobile

### ISSUE THREAD

**Issue by matiaspunx** [gdg-x/hoverboard#142]
when I scroll the image, logo and text is hidden but the bar is too big

![screenshot_2016-09-22-10-27-54](https://cloud.githubusercontent.com/assets/1827292/18752826/fb360506-80b9-11e6-9230-ca95ccbdf428.png)
![screenshot_2016-09-22-10-28-02](https://cloud.githubusercontent.com/assets/1827292/18752827/fb38aa5e-80b9-11e6-8406-a22de3eedf49.png)
![screenshot_2016-09-22-10-28-23](https://cloud.githubusercontent.com/assets/1827292/18752828/fb3a2abe-80b9-11e6-8e9a-96a964d280d0.png)

**Comment by ozasadnyy** [comment]
Fixed in d7e82ec

**Comment by matiaspunx** [comment]
TY! now it works! 👍
