### ISSUE TITLE
Speaker details - close with Escape key

### ISSUE THREAD

**Issue by joernahrens** [gdg-x/hoverboard#145]
I'd like to close the speaker details view with the Escape key. For schedules this is already working, but not for the speaker details.

## Expected outcome

ESC closes speaker details.

## Actual outcome

Nothing happens.

## Steps to reproduce

1. Open speaker details
2. Press ESC

Browser: 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by ozasadnyy** [comment]
Can't reproduce. Works for session and speakers dialogs.
