### ISSUE TITLE
Expand the Code of Conduct

### ISSUE THREAD

**Issue by juniperbelmont** [gdg-x/hoverboard#146]
The code of conduct of "don't be a jerk" misses a lot of the problems faced in tech communities of harassment and stalking. Please consider adopting a code of conduct based on something like:
- https://bocoup.com/guidelines/code-of-conduct
- http://jsconf.com/codeofconduct.html
- http://citizencodeofconduct.org/

Thanks!

**Comment by Splaktar** [comment]
GDG-X has a more complete CoC here: http://gdg-x.github.io/boomerang/#!/conduct

It would be nice to use the same one. If changes to that CoC need to be made, please submit an issue at https://github.com/gdg-x/boomerang/issues.

**Comment by ozasadnyy** [comment]
Fixed in [v1.1.0](https://github.com/gdg-x/hoverboard/releases/tag/v1.1.0)
