### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by zptoth** [gdg-x/hoverboard#1465]
**Describe the bug**
I am experiencing caching issues with hoverboard at http://www.devfest.hu

**To Reproduce**
On my own desktop I can experience the following.
Sometimes a previous, cached version of the website appears.
For example if I follow the registration link from meetup.com in this event: https://www.meetup.com/GDG-Budapest/events/262650461/

Actually the cached version still exists but the custom domain has been removed from that one and it is set at the current live version of the site + the DNS A record has been redirected weeks ago to the live site.

This has been mentioned by other users that as they see, "two versions of the site exist". These are users who have previously viewed the site, month ago.

**Expected behavior**
Only the live site should be displayed.
We cannot expect users to to use incognito window, clear cache, refresh, etc.
Especially we cannot expect them to notice the REFRESH popup in the bottom left that appears whenever any update happens on the website.

**Screenshots**
Cached older version: https://drive.google.com/file/d/1LPrr-yIjmnzL1e-EB7hXz_Wa7vlQ-1PB/view?usp=sharing
Current live version: https://drive.google.com/file/d/1z2IgSyxPlK9L5R-LVJC_AuRraMngXKip/view?usp=sharing

**Desktop (please complete the following information):**

- OS: debian 
- Browser: Chrome
- Version: 86.0.4240.75 (Official Build) (64-bit)

Any way to disable caching at all?

**Comment by zptoth** [comment]
It looks like I cannot view the current live site but only from an incognito window.
Not even a page refresh (F5) helps.

The issue is not with me. I could clear my cache but this cannot be expected from all visitors should they face this issue. And some of them seem to face it.

**Comment by zptoth** [comment]
Cached: https://devfest-hu-production.web.app/
Current live: http://devfest-bud-prod.web.app/

**Comment by zptoth** [comment]
I have opened the web.app links and noticed that when I open the current live version of the site an outdated state is loaded first, than the refresh popup appears in the bottom left. Once the page is refreshed, the right version is displayed.

Is there any way to completely get rid of this refresh method?

**Comment by abraham** [comment]
Hoverboard uses a pretty standard PWA flow that should work like this:

1. A user visits the site for the first time
1. The site renders
1. In the background the static assets are cached for offline use
1. A toast is displayed the site is ready for offline use
1. A new version of the site is deployed
1. Existing user returns
1. Cached assets are rendered immediately
1. In the background updated assets are updated
1. A toast is displayed notifying user of new version
1. User click refresh
1. Site reloads and updated assets render

Are you seeing behaviour that is different?

Hoverboard isn't currently set up to disable the offline functionality. A fairly standard [Workbox config](https://github.com/gdg-x/hoverboard/blob/main/workbox-config.js) is used though. It shouldn't be too difficult to customize.

**Comment by zptoth** [comment]
Thanks for the quick turnaround.
In my case the toast just won't come up. Not even if I refresh the page in my browser.

The offline functionality is very useful when hoverboard is used as a conference app at in person events.
Hover this is not the case anymore. There are no in person events this year so the primary use case is to use hoverboard as a website and toasts are rather uncommon at desktops, most of the users overlook them, so this is something to reconsider in my opinion.

**Comment by mhmxs** [comment]
For me only delete "Offline Web Site Data" in my Firefox solved the issue. So it means local cache was used instead of new version of the site.

**Comment by zptoth** [comment]
Thanks mhmxs!

So the question is how to resolve this issue for users who have a previous version of the site stuck in their browsers. This version doesn't even exist on the Internet anymore as that version of the site has been shut down a while ago and the content is served from a completely different source, although it's still Firebase with hoverboard.

**Comment by abraham** [comment]
If there are errors or issues that are causing users to get stuck updating from one version of Hoverboard to another I'd love to get them ironed out. Unfortunately those kinds of bugs are very hard to track down without errors or reproduction.

If you have the site available on a git repo I can access and you can tell me the commit sha of the old version and the commit sha of the new version I can take a look and try and reproduce it.

If you really want to just abandon the service worker you'd have to [disable the service worker generation](https://www.npmjs.com/package/@open-wc/building-rollup#injecting-a-service-worker) and replace it with a [no-op service worker](https://stackoverflow.com/a/38980776/26406).
