### ISSUE TITLE
Lighthouse report of the demo app...

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#151]
shows
* Cache contains start_url from manifest (alpha)
* Manifest's short_name won't be truncated when displayed on homescreen

This is a Chrome extension by Google which runs a set of tests

**Comment by MrCsabaToth** [comment]
The extension: https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?utm_source=chrome-ntp-icon

**Comment by ozasadnyy** [comment]
I knew about this extension :)
_Cache contains start_url from manifest (alpha)_ it's a new one!
_Manifest's short_name won't be truncated when displayed on homescreen_ do you have a suggestion how to make it shorter? It's can be just **DevFest 2016**

**Comment by MrCsabaToth** [comment]
Honestly, I'm not sure how serious are these. And it's already short IMHO. Clearly just an enhancement, not priority right now.
