### ISSUE TITLE
Open schedule on the todays date

### ISSUE THREAD

**Issue by zasadnyy** [gdg-x/hoverboard#153]
As a website visitor during the time of the event, I want schedule to be opened on the date of conference that is happening now.

e.g.
GDG CEE Summit was on Oct 7-9. If I open the schedule on Oct 8 I want it to opened automaticlally on Oct 8.

**Comment by tasomaniac** [comment]
As an alternative, one easy fix for this to remember the last selected date. When the user selects the 2nd day it will continue to start on that day.
