### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by vorcigernix** [gdg-x/hoverboard#154]
Hi, 
when running polymer build command, I get warning about main js file not optimized:

```
warn:    Unable to optimize .js file ../index.html_script_1.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: punc (:)',
     filename: 0,
     line: 3,
     col: 16,
     pos: 23,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous>
``` ....
Any idea what could be wrong? I tried to remove all ":" characters except required links, but can't figure out what is going wrong here.

**Comment by ndrwtrsk** [comment]
Hey, I believe we all get this warning. The application is built and runs correctly though :)

**Comment by vorcigernix** [comment]
Yeah, sure, not a big issue. I was just wondering what is going on, not an expert on build tasks myself.

**Comment by ozasadnyy** [comment]
It's because of metadata for scheme.org. 
You can delete [these lines](https://github.com/gdg-x/hoverboard/blob/master/index.html#L133), but  it can reflect on your CEO.
In any case, everything works ok, just ignore it :)
