### ISSUE TITLE
Add social sharing buttons

### ISSUE THREAD

**Issue by theyann** [gdg-x/hoverboard#156]
Hi guys,

Great job on the app.
We're using it again this year for the DevFest Belgium 2016, and this year again I have comments about "how do I share this on social media", and indeed I think it would be nice to have in the template by default a facebook and twitter share button with predefined text so that people can just click and share on their accounts.

I'll try to make a pull request when I have some time, If someone finds this idea interesting and gets it first, I'm interested also :)

Cheers,
Yannick

**Comment by ozasadnyy** [comment]
Hello @theyann , we have such functionality for blog posts and sessions details :)
Where do you expect to see them?

**Comment by theyann** [comment]
Hi and thank you so much for getting back to me so quickly :)

Well that would be nice to have those buttons somewhere on the homepage, maybe in the button bar in the top, so that someone browsing the site could easily click and share.
I imagine that technically we could setup some place the message to display in the share feature, whatever the service is, and when clicked on it allows the user to share that text directly on their social media of choice.

By default it could be some kind of a placeholder like "Come to see <NAME OF THE EVENT> in <CITY OF THE EVENT> on <DATE OF THE EVENT>" :)

what do you think?

**Comment by ozasadnyy** [comment]
I have double feelings about placing such buttons in a header. As a solution, it can be an icon which on click opens dropdown with share options

**Comment by theyann** [comment]
that's fine as well, my main point is that there is such buttons some place on the main page and it's super easy for a user to share the event on social medias ç

**Comment by theyann** [comment]
(I didn't mean to close the issue, sorry about that)
