### ISSUE TITLE
Adding partner logos to the pages, including partner logos + footer to the schedule page

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#159]
I wanted to increase the sponsor presence on the site in general. It was pretty easy (two lines) to add logo section top pages with footer. The session schedule page however doesn't have a footer. After I added both the footer and the logo section the end result is buggy: the logos and footer slips up all the way up under the header and overlaps above the schedule. I'm not sure why this is happening, since the schedule itself is also wrapped in a div.container. It also doesn't seem to be floating left or right (which would allow the footer to slip up). So far I'm loosing this CSS kung-fu match. Can anyone help?

**Comment by MrCsabaToth** [comment]
If needed I can deploy it to a separate instance, but to try this it's very simple: edit `schedule-page.html` and add

    <link rel="import" href="../elements/logos-block.html">
    <link rel="import" href="../elements/footer-block.html">

near the other element imports, and add

        <div class="container">
         <logos-block app="{{app}}" cascaded></logos-block>
         <footer-block app="{{app}}" cascaded></footer-block>
       </div>

After the existing container div and before the `session-details` within the template.

**Comment by MrCsabaToth** [comment]
Here is a deploy: https://mrcsabatoth.github.io/ (go to schedule page). I'm somewhat familiar with flexbox, I wouldn't say I am an expert. But I couldn't figure out why it's floating.

**Comment by ozasadnyy** [comment]
To achieve such result copy `<partners-block></partners-block>` (https://github.com/gdg-x/hoverboard/blob/hoverboard-v2/src/pages/home-page.html#L192) to any page you want. For instance paste here after the schedule
https://github.com/gdg-x/hoverboard/blob/hoverboard-v2/src/pages/schedule-page.html#L119
