### ISSUE TITLE
Not able to Gulp Deploy the Project

### ISSUE THREAD

**Issue by harshdattani** [gdg-x/hoverboard#16]
When I try to deply the project on Git using 'gulp deploy', I get folowing error. Whereas 'gulp serve' and 'gulp' workes perfectly.

This is the error while running gulp deploy

cmd: /bin/sh -c git rev-list --pretty=raw --max-count=1 
[22:23:27] 'deploy' errored after 11 s
[22:23:27] Error in plugin 'run-sequence'

**Comment by ozasadnyy** [comment]
Have you changed [remote url](https://github.com/gdg-x/hoverboard/blob/master/gulpfile.js#L205) ?

**Comment by harshdattani** [comment]
yes

**Comment by harshdattani** [comment]
[22:58:11] Starting 'gh-pages'...
[22:58:13] 'gh-pages' errored after 2.25 s
[22:58:13] Error in plugin 'gulp-gh-pages'
Message:
    Command failed: /bin/sh -c git rev-list --pretty=raw --max-count=1 
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]

**Comment by ozasadnyy** [comment]
Look at gulp-gh-pages [issue](https://github.com/shinnn/gulp-gh-pages/issues/42). It's not a issue related to this project
