### ISSUE TITLE
Feature request: being able to display a list of resources (presentation materials, slides, URLs) for the sessions

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#161]
This can be an additional field for sessions in the sessions.json, the field would be an array of the resources. The sessions-details.html would have a new section and would iterate over these. Maybe in the future the presenters themselves could even upload them, but for now the organizers can gather them and update the site. I may implement this pretty soon.

**Comment by ozasadnyy** [comment]
We already have a way to add presentations and session recording to the dialog: https://github.com/gdg-x/hoverboard/blob/master/src/elements/session-details.html#L91

**Comment by MrCsabaToth** [comment]
Oh, I haven't realized. Then I may just modify my fork to accept a list of URLs and files instead of a single one.
