### ISSUE TITLE
Unidirectional data flow & Redux

### ISSUE THREAD

**Issue by filipproch** [gdg-x/hoverboard#174]
Hi,

I suggest, before adding too many features including firebase to move to unidirectional data flow and Redux. It's recommended pattern for web applications and removes complexity and decreases the possibility of bugs related to work with data. With the recently added/in progress feature of my schedule incorporating work with data, it would be good as you are planning more advanced features like adminitration.

**Comment by ozasadnyy** [comment]
@filipproch good point. I was also thinking about moving to redux. But I suggest postponing this migration until Polymer 2 release. Then we will be able to modify our elements for this needs.
