### ISSUE TITLE
unable to deploy to firebased

### ISSUE THREAD

**Issue by osvaldoM** [gdg-x/hoverboard#179]
after deploying to firebase using the commands suggested in the docs, my website simply doesnt work, apparently the data and images folder are not added to the build folder..
even after manually adding them, it still does not work.
here is my firebase,json

` "hosting": {
    "public": "./build/bundled",
    "cleanUrls": true,
    "rewrites": [
      {
        "source": "**/*",
        "destination": "/index.html"
      }
    ],
    "ignore": [
      "/test/**",
      "bower.json",
      "database.rules.json",
      "firebase.json",
      "README.md"
    ]
  }`

and this is what i get in the browser
![image](https://cloud.githubusercontent.com/assets/11247633/19957596/a3e9926a-a1a0-11e6-88b6-070bcf6c1fad.png)

**Comment by ndrwtrsk** [comment]
Did you `polymer build` ?

**Comment by osvaldoM** [comment]
yes i did @ndrwtrsk ..
here are the contents of build/bundled folder
![image](https://cloud.githubusercontent.com/assets/11247633/19958332/1b9879d8-a1a7-11e6-9500-f9f167e63e85.png)

**Comment by ndrwtrsk** [comment]
You are missing quite a bit of stuff, is your build successful at all? In
my build I have all that stuff:

```
/home/andrzejtorski/Repos/df16pl/build/bundled/bower_components
/home/andrzejtorski/Repos/df16pl/build/bundled/data
/home/andrzejtorski/Repos/df16pl/build/bundled/images
/home/andrzejtorski/Repos/df16pl/build/bundled/scripts
/home/andrzejtorski/Repos/df16pl/build/bundled/src
/home/andrzejtorski/Repos/df16pl/build/bundled/bower.json
/home/andrzejtorski/Repos/df16pl/build/bundled/index.html
/home/andrzejtorski/Repos/df16pl/build/bundled/manifest.json
/home/andrzejtorski/Repos/df16pl/build/bundled/service-worker.js
```

czw., 3.11.2016 o 08:23 użytkownik Code Coder <notifications@github.com>
napisał:

yes i did @ndrwtrsk <https://github.com/ndrwtrsk> ..
here are the contents of build/bundled folder
[image: image]
<https://cloud.githubusercontent.com/assets/11247633/19958332/1b9879d8-a1a7-11e6-9500-f9f167e63e85.png>

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/gdg-x/hoverboard/issues/179#issuecomment-258077355>,
or mute
the thread

**Comment by ndrwtrsk** [comment]
You are missing quite a bit of stuff, is your build successful at all? In
my build I have all that stuff:

```
/home/andrzejtorski/Repos/df16pl/build/bundled/bower_components
/home/andrzejtorski/Repos/df16pl/build/bundled/data
/home/andrzejtorski/Repos/df16pl/build/bundled/images
/home/andrzejtorski/Repos/df16pl/build/bundled/scripts
/home/andrzejtorski/Repos/df16pl/build/bundled/src
/home/andrzejtorski/Repos/df16pl/build/bundled/bower.json
/home/andrzejtorski/Repos/df16pl/build/bundled/index.html
/home/andrzejtorski/Repos/df16pl/build/bundled/manifest.json
/home/andrzejtorski/Repos/df16pl/build/bundled/service-worker.js
```

**Comment by osvaldoM** [comment]
thank you @ndrwtrsk I notticed there was an error in my build process so i added all the files you mentioned manually and it is working on  [https://devfestmaputo.firebaseapp.com/](url) now ...

**Comment by ndrwtrsk** [comment]
Glad to hear it, @osvaldoM :)

**Comment by ozasadnyy** [comment]
@osvaldoM which version of Polymer-cli do you have? 
`polymer --version`

**Comment by osvaldoM** [comment]
@ozasadnyy  it's `0.16.0`

**Comment by ozasadnyy** [comment]
@osvaldoM please show me console output of `polymer build`?

**Comment by ndrwtrsk** [comment]
I believe it's working now @ozasadnyy ;)
