### ISSUE TITLE
Please use granular commits, instead of huge squashed "release" commits

### ISSUE THREAD

**Issue by dbs** [gdg-x/hoverboard#180]
7a6ac8a0ff2 was a monster commit that touched 34 files and almost 2,000 lines of code, mixing around 60 different features and bug fixes. Merging that into our own deployed codebase took hours because it was one monolithic commit that caused a number of merge conflicts that we needed to sort out first. This seems to have been the style for the "release" commits of the past as well.

If the features and bug fixes are instead merged as individual commits into master and then tagged as a release--a more typical git workflow--it would be much easier for us (and I suspect other sites) to rapidly cherry-pick and deploy the bug fixes, and merge the new features on an as-needed basis later.

**Comment by ozasadnyy** [comment]
Thanks @dbs for the feedback and sorry for this. We will try to omit such things with next releases.

**Comment by tasomaniac** [comment]
👍 for that. 

I guess GDG Istanbul is on version 1.0. I started using it before 1.0 and it was really hard to merge 1.0. The new my schedule feature is really really cool but I don't know if I can merge that back. I tried but there were lots of conflicts. 

But anyways, we don't really have to upgrade it. It is not a must. Our site just works now. 

Maybe trying to be granular only on bug fix commits would be enough. And also those bug fixes can be cherry picked and applied on top of the old version and release `1.0.1` for example. Just with the bug fixes along with `1.1` release. But that is additional work of course. We can do it only if the bugs are critical.

**Comment by ozasadnyy** [comment]
You can always do a cherry pick from a develop branch for now. @tasomaniac, there are bug fixes I recommend to merge. It should be easy to do If you have changed only data.

**Comment by tasomaniac** [comment]
It is hard to identify which ones are bug fixes. I think there will be less conflicts with bug fixes but they are hard to identify. If I try to merge all, then there will be lots of conflicts. 

If you can maybe cherry pick bug fixes on to version `1.0` and then release another `1.0.1` with just the bug fixes but with no new features, then it will be easier for users to merge the bug fixes.
