### ISSUE TITLE
Cannot configure facebook share data

### ISSUE THREAD

**Issue by sembozdemir** [gdg-x/hoverboard#181]
Hi,

I want to configure facebook sharing data which shows up when user click the share icon on the footer. I edited facebook, g+ and twitter data on index.html successfully. However, when I want to share the website on facebook, it still gives me old data. What should I do to fix it?

There is the code related with sharing meta data on index.html

      
      <meta itemprop="name" content="GDG DevFest İzmir 2016">
      <meta itemprop="description"
            content="Birbirinden renkli konuşmacılar ile tüm gün boyunca teknoloji ve inovasyon konuşmaya, yenilikleri öğrenmeye ve sizin gibi teknoloji meraklılarıyla tanışmaya davetlisiniz.">
      <meta itemprop="image" content="/images/social-share.png">
      <meta itemprop="startDate" content="2016-10-27T09:00:00+03:00">
      <meta itemprop="endDate" content="2016-10-28T19:00:00+03:00">

      
      <meta property="og:title" content="GDG DevFest İzmir 2016">
      <meta property="og:site_name" content="GDG DevFest İzmir 2016">
      <meta property="og:type" content="website">
      <meta property="og:url" content="https://devfestizmir.firebaseapp.com/">
      <meta property="og:description"
            content="Birbirinden renkli konuşmacılar ile tüm gün boyunca teknoloji ve inovasyon konuşmaya, yenilikleri öğrenmeye ve sizin gibi teknoloji meraklılarıyla tanışmaya davetlisiniz.">
      <meta property="og:type" content="Event">
      <meta property="og:image" content="/images/social-share.png">
      <meta property="og:image:type" content="image/png" />

      
      <meta name="twitter:card" content="summary_large_image">
      <meta name="twitter:creator" content="@izmirgdg">
      <meta name="twitter:title" content="GDG DevFest İzmir 2016">
      <meta name="twitter:description"
            content="Birbirinden renkli konuşmacılar ile tüm gün boyunca teknoloji ve inovasyon konuşmaya, yenilikleri öğrenmeye ve sizin gibi teknoloji meraklılarıyla tanışmaya davetlisiniz.">
      <meta name="twitter:image" content="/images/social-share.png">

**Comment by abraham** [comment]
The Facebook Sharing Debugger tool is a great way to debug issues like this.

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdevfestizmir.firebaseapp.com%2F

On my first check it said that the details had last been updated on Nov 1st. I told it to "scrape again" and now it seems to mostly match what you currently have. Although Facebook doesn't seem to like the `og:image` URL.

> Provided og:image URL, /images/social-share.png was not a valid URL.

**Comment by sembozdemir** [comment]
Thanks @abraham for your answer.

Image is actually here "https://devfestizmir.firebaseapp.com/images/social-share.png" and valid. I could not understand why it does not work. I edited index.html again. (social-share.jpg -> social-share.png)

**Comment by sembozdemir** [comment]
I fixed it by giving full url. 

      <meta property="og:image" content="https://devfestizmir.firebaseapp.com/images/social-share.png">
