### ISSUE TITLE
Schedule doesn't load on first load on large dataset

### ISSUE THREAD

**Issue by ndrwtrsk** [gdg-x/hoverboard#185]
Hey on https://devfest.pl/schedule/day1 we're experiencing something odd, on first load of this page, no agenda is displayed. You have to either reload the page or return to this from page from somewhere else.

Has anyone experienced anything of that sort?
I'll admit we have a hefty size of sessions and tracks and maybe that's why that is happening?

**Comment by twhetzel** [comment]
It loaded fine for me from mobile on WiFi. It does take a few (1-3) seconds
for the schedule to display.

Trish

**Comment by ozasadnyy** [comment]
@ndrwtrsk do you still have this issue?

**Comment by ndrwtrsk** [comment]
@ozasadnyy it's fixed with the latest release of Hoverboard :)

**Comment by sembozdemir** [comment]
Hi @ndrwtrsk, what is the latest release? Is it v.1.2.0?

I have this issue in Safari Mobile specially. I use v1.2.0
