### ISSUE TITLE
Move all chapter/event specific variables into a single file

### ISSUE THREAD

**Issue by mkpartnersDev1** [gdg-x/hoverboard#19]
It'd be great if all chapter specific references were in a single data file.  Things like GDG Chapter name, Social Links, dates, location, etc.

**Comment by ozasadnyy** [comment]
Hello @mkpartnersDev1 . Thanks for the proposition. I know that all information should be separated from code, but for now I don't know which solution would be the best for this project. For now I am developing new features that will be useful for events. In the future, we will find out the best way to make this happen.

**Comment by tasomaniac** [comment]
Is this done now? @ozasadnyy

**Comment by ozasadnyy** [comment]
Hopefully, with #100 everything will be easier.
