### ISSUE TITLE
Change icon that mark session in my schedule

### ISSUE THREAD

**Issue by zasadnyy** [gdg-x/hoverboard#197]
"minus" icon on the session card added to my schedule is confusing. I'd suggest to replace with with a checked box ☑︎ or a star ☆ (in this case in the session details popup you can display filled or empty star)

**Comment by ozasadnyy** [comment]
⭐️ will be used later for rating.
We can change with these icons:
![image](https://cloud.githubusercontent.com/assets/2954281/20748211/f4ec64fc-b6f5-11e6-9899-b12b3122f6d1.png)

**Comment by zasadnyy** [comment]
Yup, it should work
