### ISSUE TITLE
Not working in iOS 15

### ISSUE THREAD

**Issue by resand-finerio** [gdg-x/hoverboard#2039]
**Describe the bug**
The load sections no working. 

**Screenshots**
![image](https://user-images.githubusercontent.com/79542161/142408469-643d4c34-dd69-4d0e-9275-e77342fb5349.png)
**Smartphone:**

- Device: iPhone 13 Pro
- OS: iOS 15.1
- Browser Safari

**Comment by abraham** [comment]
What's not working?

**Comment by resand-finerio** [comment]
It does not navigate to the section, it only shows the image that I attach.

**Comment by abraham** [comment]
So you can't scroll and tapping the menu button doesn't do anything? Can you look at the web debugger and see if there are any error messages? https://www.browserstack.com/guide/how-to-debug-on-iphone

**Comment by resand-finerio** [comment]
I click on the speakers menu for example and it does nothing.

Attached are images and video.

<img width="1035" alt="Captura de Pantalla 2021-11-18 a la(s) 10 58 27 p m" src="https://user-images.githubusercontent.com/79542161/142568113-45841d02-eaba-4892-80bf-4428e4e09ade.png">

<img width="1035" alt="Captura de Pantalla 2021-11-18 a la(s) 10 59 03 p m" src="https://user-images.githubusercontent.com/79542161/142568121-688266d6-11a4-4113-9ced-4370579c2749.png">

https://user-images.githubusercontent.com/79542161/142568187-6fd7bcec-fa82-44ef-a704-43079c3ed4e9.mov
