### ISSUE TITLE
[Roadmap] Hoverboard v2

### ISSUE THREAD

**Issue by ozasadnyy** [gdg-x/hoverboard#206]
❎ - create cleaner design
☑ - migrate to Polymer 2
☑ - leverage an unidirectional flow with Redux

**Comment by ozasadnyy** [comment]
Done in 443dbb7d9966b3e8b2b5dd009dc4e14bbc7c8a1c

**Comment by cliveb** [comment]
Any plans to support Polymer 2.0 in current Hoverboard template before Hoverboard 2.0?

Cross-post on glitter.im chat. Because need stable web site for DevFest 17.

**Comment by ozasadnyy** [comment]
Hello @cliveb , not from our side. We are focused on v2, but we will appreciate any PR
