### ISSUE TITLE
Add possibility to create long sessions

### ISSUE THREAD

**Issue by ozasadnyy** [gdg-x/hoverboard#207]
Current solution is not cool
![image](https://cloud.githubusercontent.com/assets/2954281/21408730/4187cdca-c7df-11e6-99b0-ca112b37359e.png)

**Comment by MrCsabaToth** [comment]
A little unrelated but I needed to make changes both for WTM2017 and valleydevfest2016 websites to handle all track wide sessions well. We wanted to display location, but those usually none of the classrooms. So I mark those sessions with a special "colspan" JSON field and add session level "location" field.

**Comment by ozasadnyy** [comment]
@MrCsabaToth can you show an example?

**Comment by ozasadnyy** [comment]
Done
![image](https://user-images.githubusercontent.com/2954281/42409192-28912788-81df-11e8-8654-8372e7d503b6.png)
