### ISSUE TITLE
Add session ratings

### ISSUE THREAD

**Issue by ozasadnyy** [gdg-x/hoverboard#211]
Available only for authorized users. Save ratings data to Firebase DB
Also, add labels on hover. 
![image](https://cloud.githubusercontent.com/assets/2954281/21455821/0cf24524-c92c-11e6-878a-05726b08d047.png)

**Comment by MrCsabaToth** [comment]
I had detailed implementation of this last year:
![rating](https://cloud.githubusercontent.com/assets/744949/22097306/53116a36-ddd5-11e6-8a6f-a1bde27e68b5.png)

I had 3 categories: Content, Presentation and Venue. When you click on the star, the 5 selection pops up. Plus there's a comment, which can be extremely valuable!
In action: https://valleydevfest.com/schedule/day1?sessionId=131

I gathered the data into FireBase, and after the conference I processed individual detailed analysis for the speakers, like https://vdf2016r.firebaseapp.com/?uuid=88f89a48c8344fb7af3e5c7616c9a30d
(Processing source code, a node app: https://github.com/gdgfresno/processRatings
Individual static websites source: https://github.com/gdgfresno/vdf2016r/tree/gh-pages)

Aggregate statistics:
https://wdf2016whole.firebaseapp.com/
(static website src https://github.com/gdgfresno/vdf2016whole)
