### ISSUE TITLE
Schedule information doesn't work in Firefox

### ISSUE THREAD

**Issue by philnash** [gdg-x/hoverboard#23]
Trying to view information about a scheduled session is not possible in Firefox (tested in version 42, works in Chrome, Opera and Safari). Reproduced in both [GDG DevFest London](http://devfest.gdg-london.com/) and the reference [GDG DevFest Ukraine](https://devfest.gdg.org.ua/) app.

Clicking on the title of a session in the schedule causes a `ReferenceError`:

```
ReferenceError: event is not defined
```

The file this occurs in seems to be a generated data file (not sure how this works exactly!). Reading the data it seems the issue is in the Polymer element `schedule-block` at this function:

```javascript
        _sessionTap: function() {
            page.redirect('/schedule/' + event.model.subSession.id);
            this._openSession(event.model.subSession);
        },
```

Should that function take an event as an argument?

**Comment by ozasadnyy** [comment]
Thank you @philnash for submitting issue. I have missed argument.

**Comment by philnash** [comment]
No problem, thanks for sorting! Makes me wonder how it worked in the other browsers, but glad this fixes it!
