### ISSUE TITLE
npm run firestore:copy don't work: then is not a function

### ISSUE THREAD

**Issue by benju69** [gdg-x/hoverboard#2313]
**Describe the bug**
npm run firestore:copy don't work
 
i have an error in script :
hoverboard/scripts/firestore-copy/index.ts:6
  .then((data) => saveData(data, destination))
^ TypeError: (0 , utils_1.getData)(...).then is not a function

Is this normal ? Also should i update project ?

**To Reproduce**

1. have a collection json
2. run the npm firestore:copy command
3. See error

**Expected behavior**
data added to firebase

**Comment by abraham** [comment]
`npm run firestore:copy team team.json` ran successfully for me on the latest code. You might need to update.

**Comment by benju69** [comment]
And in the other direction ? like npm run firestore:copy team.json team
