### ISSUE TITLE
generatedSchedule is not saved/generated

### ISSUE THREAD

**Issue by benju69** [gdg-x/hoverboard#2322]
**Describe the bug**
generatedSchedule is not saved/generated 
How i can know what the issue is ? what is wrong in my schedule?

**To Reproduce**
copy schedule data to firestore
npm run deploy

on /schedule page: Error loading schedule.
In firestore: I don't have generatedSchedule collection 

**Expected behavior**
Schedule is here

**Comment by solstarz** [comment]
@benju69 maybe i can ask you.
How did you manage to connect firestore database to the project?
For some odd reason the project only connects to the realtime database...

In which it results in that the schedule page is empty with no data to see even so for the speakers page..

If you can point me in the right direction i will be a happy person..

Thanks in advance.

JP

**Comment by benju69** [comment]
> @benju69 maybe i can ask you. How did you manage to connect firestore database to the project? For some odd reason the project only connects to the realtime database...
> 
> In which it results in that the schedule page is empty with no data to see even so for the speakers page..
> 
> If you can point me in the right direction i will be a happy person..
> 
> Thanks in advance.
> 
> JP

You must have a really old project, hoverboard is using firestore now
you should at least have the speakers, look the structure in docs/default-firebase-data.json, then you can deploy this file with npm run firestore:init

**Comment by solstarz** [comment]
> 

Well, im using the most recent project, according to setup page https://github.com/gdg-x/hoverboard/blob/main/docs/tutorials/00-set-up.md

But for some odd reason when you look at the settings (url)__/firebase/init.json the databaseUrl is the url for the realtime database and not the firestore database..

Somewhere im missing something..

**Comment by abraham** [comment]
@solstarz `__/firebase/init.json` has the entire config for the project and will include `databaseUrl` with the realtime database URL regardless if it's being used. This is expected. Please keep the discussion on #2321 so that it's all on one thread.

**Comment by benju69** [comment]
Thanks for the clarification
well i don't really see errors in the logs

scheduleWrite
Function execution took 3482 ms, finished with status: 'ok'

**Comment by benju69** [comment]
I have some errors with prerender (but no more information)

5:00:07.156 PM
prerender
Function execution started
5:00:10.257 PM
prerender
Function execution took 3102 ms, finished with status: 'crash'

**Comment by benju69** [comment]
I have this warning on scheduleWrite:
severity: "WARNING"
textPayload: "Snapshot has no readTime. Using now()"
