### ISSUE TITLE
Hoverboard compatible on IOS?

### ISSUE THREAD

**Issue by solstarz** [gdg-x/hoverboard#2351]
**Describe the bug**
Hoverboard compatible on IOS?
I tested the webapp on IOS and i can only see a whitescreen

**To Reproduce**
Open the webapp on a IOS device

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone12]

**Comment by abraham** [comment]
I'm seeing blank pages maybe 20% of the time on local dev and maybe 80% of the time on hoverboard-master.web.app. No obvious errors though so maybe it's a weird race condition.

**Comment by abraham** [comment]
I'm still looking into this. It's behaving as though Safari randomly decides not to execute imported Javascript file.

**Comment by abraham** [comment]
It's something to do with the service worker. Commenting out `<script src="./src/service-worker-registration.ts" type="module"></script>` in `index.html` doesn't show the issue anymore locally which is really weird since in local development nothing is being cached.

**Comment by solstarz** [comment]
@abraham thanks for taking a look.

I will do what you did

**Comment by solstarz** [comment]
@abraham it works!! Thanks again!!

**Comment by abraham** [comment]
I don't really recommend just disabling a service worker. It can lead to weird behavior for users that already the service worker installed. It's probably the best temporary fix until the root cause if identified though.

**Comment by solstarz** [comment]
@abraham ah got it.. Im guessing it will take some digging to get to the root cause..

**Comment by abraham** [comment]
It appears that it's caused by #2148. Still looking into what specifically.
