### ISSUE TITLE
Sign-in is broken

### ISSUE THREAD

**Issue by benju69** [gdg-x/hoverboard#2364]
**Describe the bug**
I have same issue as here: https://github.com/gdg-x/hoverboard/issues/1335
I click on sign in with google
A dialog opens for some seconds and disappears.
Not logged, can't save the sessions

**Expected behavior**
I guess something is missing in firebase
Documentation should have information about the sign in: how it works, how to configure it, what it does ?

**Comment by benju69** [comment]
Ok I found how to activate
It's in Authentication section/Sign in method, add Google as new provider
but now I have the "My Schedule" tab but it's empty, any idea ?

**Comment by abraham** [comment]
I've created #2366 to improve auth documentation.

For the blank "My Schedule" I think you need this change. https://github.com/gdg-x/hoverboard/commit/a1541b1d5529f485b7c3e4315d3faa3dfd53492d#diff-1a8c8378553dfd6438608db25b054dd546669c2958d8952480d6304136411735
