### ISSUE TITLE
Add new Content page

### ISSUE THREAD

**Issue by PierreAmmeloot** [gdg-x/hoverboard#238]
I want add a new content page similar at "Code of Conduct" page.
Same as this FAQ page : https://devfest.gdgnantes.com/faq/
Can you write a guidelines for me?

**Comment by anxolerd** [comment]
Hi! I'm not a contributor of hoverboard project but I can try to explain. N.B. all my explanations are based on https://github.com/GDG-Nantes/devfest2017/commit/ddc94bb8d98f93b28bd674bf3c124a4879f07143 (the commit which adds the FAQ page of GDG-Nantes) and does not pretend to be 100% correct. However it works.

1. under `src/pages` directory create `faq-page.html` template with the desired logic of display
2. add newly created file to the `fragments` section of `polymer.json`
3. add permanent (desired) route to your new page `data/hoverboard.config.json` under the `navigation` section. Now it will appear as link with empty text in the navigation bar in header. Use existing entries in the section as reference
4. add page description (page title, background, etc) to `data/hoverboard.config.json` under the `pages` section. Use existing page desctiptions as reference.
5. add page to template mapping to `src/hoverboard-app.html` inside the `neon-animated-pages` tag. Use the existing mappings as reference. Now you have your page displayed under the desired url.

Now it is time to add some real data. The good practice is to store data in the `data` directory. 

6. Create file `faqs.json` in the `data` directory. Add there your data in JSON. It is likely be a list of objects you can iterate over.
7. bind data to the app attribute. Add the following line in the `src/elements/app-data.html` to the `template` tag:
  
  ```
  <iron-ajax auto url="[[faqsSource]]" 
                  handle-as="json"
                  last-response="{{app.faqs}}"></iron-ajax>
  ```

  Add a mapping in the component's `script` tag  as well: 

  ```          
faqsSource: {
  type: String,
  value: '/data/faqs.json'
},
  ```
However you might want to use dynamic content from Firebase. For this case you may want to take a look at the commented code in `src/elements/app-data.html`.

**Comment by ozasadnyy** [comment]
@PierreAmmeloot , sorry I have missed your issue :(
@anxolerd everything is correct. This is why I love Open Source projects, thank you so much 👍
