### ISSUE TITLE
Rating was not functioning well for me: not grouped under the ratings path, permission_denied

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#241]
Before the last big merge from develop branch to the main it was working. However it was recording the rating not into /ratings/$uid/... (like the schedule is grouped inder /userSessions/ and the setting is /userSessions/$uid/{sessionId} = true), but instead directly into the root, by /$uid/sessions/{sessionId} = x. Here is the console error message: `FIREBASE WARNINGL set at /7D9gkjdhkfjghgfkhgqaq2/sessions/136 failed: permission_denied`.

Now, since the merges the database rules do expect the info to be grouped under `/ratings` and not just directly in the root: https://github.com/gdg-x/hoverboard/blob/master/database.rules.json#L5 and that is desirable once a ton of user will rate. Why the app tries to put it under the root?

This seems to be a copy-paste error: `id="userSessions"` for a `ratingsPath` document https://github.com/gdg-x/hoverboard/blob/master/src/elements/session-details.html#L81 (copied from https://github.com/gdg-x/hoverboard/blob/master/src/pages/schedule-page.html#L52)

Unfortunately that didn't fix it yet. I'd like to store the rating grouped under the ratings. Now, I might as well made a mistake during my last merge. Schedule persistence is working OK. I'm working from the `develop` branch, my source is here: https://github.com/gdgfresno/WTM2017/tree/develop (we are gearing up for a WTM conference coming up in two weeks).

**Comment by MrCsabaToth** [comment]
Maybe an older service worker got stuck, now it works. I still think that the copy-paste error I mention is one to better fix. What do you think about https://github.com/gdgfresno/WTM2017/commit/f60d8b9174a62858e30dac07d63960cee6f044e4 ?

**Comment by sophieH29** [comment]
Hello @MrCsabaToth, thanks for mentioning copy paste error with id, that does not have much impact. Anyway,  it will be fixed.
Good to know that you solved your problem. From your [commit](https://github.com/gdgfresno/WTM2017/commit/f60d8b9174a62858e30dac07d63960cee6f044e4) I see that the issue was with hoverboard.config.json which was missing rating path, right?
I've just tried master, it works properly, configs are correct.

**Comment by MrCsabaToth** [comment]
Hmm, I thought the `ratingPath` was missing from hoverboard too, but it's there.
