### ISSUE TITLE
Is localization gone?

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#243]
The localized resources disappeared, and I don't see the languages selector either. Is it lurking somewhere? I localized valleydevfest 2016 to Spanish and Hmong (+Armenian and Arabic). I planned to localize again to at least Spanish and Hmong again

**Comment by ozasadnyy** [comment]
Yes, in [v1.2.0](https://github.com/gdg-x/hoverboard/pull/235) we have removed i18n because it adds much more complexity to the app

**Comment by MrCsabaToth** [comment]
Ok. I'll see how hard is to add it back for my event.

**Comment by ozasadnyy** [comment]
I don't want to add [app-localize-behavior](https://github.com/PolymerElements/app-localize-behavior). Ideally, we need to generate a separate application with another localization.

**Comment by MrCsabaToth** [comment]
Don't add. I admit that for those who don't need localization it added complexity. Will you come to global GDG summit? I want to chat a lot about hoverboard.

**Comment by ozasadnyy** [comment]
Yes :) Hopefully with a Hoverboard v2
