### ISSUE TITLE
Deploying Always Return Error on Github Actions

### ISSUE THREAD

**Issue by vzrenggamani** [gdg-x/hoverboard#2445]
**Describe the bug**
When I first tried to deploy this application, I always got a series of errors in github actions, including:
1. `npm ci` does not sync in functions folder.
2. `firebase realtime database` has not been setup.

**To Reproduce**
1. Fork the repository and Clone like usual
2. Open the project folder, run `npm install` on functions folder first, the lockfile is outdated.
3. go back to root folder, and run `npm ci`, wait until finish
4. Create the serviceaccount using setup guide instructions.
5. Init firestore databases.
6. run the `npx firebase init hosting:github` thingy and make secure github secrets are added.
7. change the YAML workflow
8. push the changes.
9. The build will return error both on deploy workflow exactly at `uses: w9jds/firebase-action@v2.0.0` step and main workflow at `test` step.
10. The deployment fail.

**Expected behavior**
It should be deployed without any problems, it cloned perfectly.

- OS: Windows 11
- Browser Chrome v100
- Cloned commit a6284a4db4a9948f57f2286579342467bff830e0
- NodeJS v16.15 & npm v8.9

**Additional Context**
![image](https://user-images.githubusercontent.com/14950309/174469529-f697a195-424d-4c5f-a81e-36ac76c3a1e4.png)
Its error and blank screen returned by the `npm start` while trying to access the webpage..

**Comment by abraham** [comment]
I just did a refresh of the lock files. It seems to be running `npm ci` fine now.

It looks like you're hosting on gitpod. Hoverboard only supports Firebase Hosting unless you make some custom modifications to how configuration is loaded.

**Comment by vzrenggamani** [comment]
Just found out the miss configuratiion, I think we need to update the documentation while creating the firebase account. We need to `create web app` and added web app configuration instead only the serviceaccount json, the new firebase deployment need project appid.

```js
const firebaseConfig = {
  apiKey: "omitted--Cusi3qmm4YUAg9tMIXG0",
  authDomain: "omitted.firebaseapp.com",
  databaseURL: "omitted-southeast1.firebasedatabase.app",
  projectId: "festival-kreatif",
  storageBucket: "omitted.appspot.com",
  messagingSenderId: "omitted0204",
  appId: "omitted279c898664b05ba9",
  measurementId: "omittedBQ9X"
};
```
