### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by twhetzel** [gdg-x/hoverboard#25]
I downloaded the latest version (DL on 11/13/2015) and am getting an error when running gulp serve:
Polymer.dom(...).observeNodes is not a function

**Comment by ozasadnyy** [comment]
Hello @twhetzel . Give full stack strace

**Comment by tomasite** [comment]
<img width="932" alt="capture d ecran 2016-02-04 a 23 45 03" src="https://cloud.githubusercontent.com/assets/725084/12832314/7cfcfdaa-cb99-11e5-9220-6246fceff786.png">
Hello @ozasadnyy I have the same problem as @twhetzel, let me know if you need more info.
Thanks in advance for your help.

**Comment by ozasadnyy** [comment]
Hey, @tomasite . Try to update iron-overlay-behavior to the last version.
in (bower.json)[https://github.com/gdg-x/hoverboard/blob/master/bower.json] add new line in _dependencies_
```
 "iron-overlay-behavior": "PolymerElements/iron-overlay-behavior#1.2.x",
```

**Comment by tomasite** [comment]
@ozasadnyy thanks for your answer but unfortunately it doesn't work either...
I don't think this is related directly to the problem but when I run ```bower instal``` the following question prompts (and as you see I choose the one required by the project, the same for google-analytics btw).
<img width="744" alt="capture d ecran 2016-02-05 a 21 02 16" src="https://cloud.githubusercontent.com/assets/725084/12857730/1541b242-cc4c-11e5-87f5-ac72f7c2bcf9.png">
Thanks again for your support.

**Comment by ozasadnyy** [comment]
The last think is not the problem. It just show that you can update dependencies. I will try locally on my computer and tell you what to select

**Comment by ozasadnyy** [comment]
I have updated bower.json.
During installation, please choose the following items:
```
Unable to find a suitable version for google-analytics, please choose one:
    1) google-analytics#~0.1.0 which resolved to 0.1.0 and is required by hoverboard
    2) google-analytics#^1.0.0 which resolved to 1.2.1 and is required by google-web-components#1.0.1
```
1) google-analytics#~0.1.0 which resolved to 0.1.0 and is required by hoverboard

**Comment by tomasite** [comment]
@ozasadnyy thanks a lot, it works like a charm now!

**Comment by ozasadnyy** [comment]
Nice! But I want to warn you, that next version of the project will have breakable changes.
