### ISSUE TITLE
Choose Date format from HoverBoard Config

### ISSUE THREAD

**Issue by davinkevin** [gdg-x/hoverboard#258]
Hi, 

Before doing a PR, I would like to check if the solution I propose fit well with the problematic (maybe a better solution exits 😄 )

After this issue (https://github.com/GDGToulouse/site-devfest-toulouse-2017/issues/45), we would like to show the date in the blog part of the site in the FR format. 

To do so, I have put some information into the `hoverboard.config.json` under the key `date` and have add the `locale` and the format object which should be use in the section of the site (the blog in this example).

So we have something like this : 
```json 
...
"date": {
        "locale": "fr-FR",
        "blog": {"month": "short", "day": "numeric", "year": "numeric"}
    },
...
```

Then, I use the nunjucks to inject the value where I need, in this case in the `post-page.html`. It seems to be the only place where we define a date which should be displayed in the web part. I modified the JS like this : 

```js
...
_postChanged: function () {
          if (this.postId) {
            var postIndex = this._getIndexByProperty(this.posts, 'id', this.postId);

            this._latestPosts[0] = postIndex > 0 ? this.posts[postIndex - 1] : null;
            this._latestPosts[1] = postIndex < this.posts.length - 1 ? this.posts[postIndex + 1] : null;
            this.notifyPath('_latestPosts', this._latestPosts.slice());

            this._post = this.posts[postIndex];
            this._updateHeaderSettings();
            this.notifyPath('_post.date', new Date(this._post.posted).toLocaleString('{$ date.locale $}', {$ date.blog | dump | safe $}));

            this._postUrl = '/data/posts/' + this._post.posted + '-' + this.postId + '.markdown';
            this.$.ajax.generateRequest();
          }
        },

        _postLoaded: function () {
          this.postId = null;
          HOVERBOARD.Analytics.trackEvent('blog', 'open post', this._post.title);
        },

        _updateHeaderSettings: function () {
          if (this._post) {
            this.set('app.headerSettings', {
              backgroundColor: this._post.primaryColor,
              backgroundImage: this._post.image,
              fontColor: '#fff',
              tabBarColor: '#fff',
              title: this._post.title,
              subtitle: new Date(this._post.posted).toLocaleString('{$ date.locale $}', {$ date.blog | dump | safe $})
            });
          }
        }
...
```

I use the `toLocaleString` method with the `Locale` define in conf and the object format as parameter to let us define the format. 

What do you think of this ? I would like to do a PR but don't know if this fits your need or if a better way to do that is available.

You can check the commit described in this issue here : https://github.com/GDGToulouse/site-devfest-toulouse-2017/commit/e58c7d6431e53d44dd42251ee4d043b266cbf527

Thanks

**Comment by ozasadnyy** [comment]
hmm, interesting. We personally don't need such functionality but if you need this, other people probably needs this as well :)
I would rather rename `"date"` to `"dateFormat"` and set English locate to default for Hoverboard.

Thanks for your ideas 👍

**Comment by davinkevin** [comment]
A small comment to let you know this feature isn't present in the v2. 

Could you re-open the issue, I will backport this in a new PR?

/cc @scraly
> https://github.com/GDGToulouse/site-devfest-toulouse-2018/issues/18
