### ISSUE TITLE
[docs] Updating the getting started guide

### ISSUE THREAD

**Issue by vzrenggamani** [gdg-x/hoverboard#2717]
**Is your feature request related to a problem? Please describe.**
Its very hard to deploy the apps using the old guides, many things has changed since firebase keeping how to deploy and the interconnected services like appengine and so on, even the config file also have newer versions.

I had problems with `rm -rf dist` which is not supported by the powershell / cmd.

**Describe the solution you'd like**
It would lovely to have most recent documentation about how to run and deploy the apps, including the environments.

**Comment by abraham** [comment]
I'd recommend using [WSL](https://learn.microsoft.com/en-us/windows/wsl/about) locally.

Are there specific parts of the docs that don't match up with Firebase UI now?

**Comment by vzrenggamani** [comment]
I can run it locally without problems with windows, despite need to remove the `npm clean` due to `rm -rf` command does not recognise in Windows System. But when I need to deploy the app, it thrown error we need to enabled the Google App Engine stuff. It seems nothing to worry about but it may confuse people who thinking "I can run it on Firebase Free Plan".

I would like to help but even I am cannot deploy it 😢
