### ISSUE TITLE
Build Issue (Windows 10)

### ISSUE THREAD

**Issue by envy7** [gdg-x/hoverboard#28]
![issue1](https://cloud.githubusercontent.com/assets/12188993/12866839/74b104ba-cd02-11e5-9f94-5dd46b935b56.png)
![issue2](https://cloud.githubusercontent.com/assets/12188993/12866840/74cb027a-cd02-11e5-929f-dc2304595ce5.png)

While trying to bulid there were several dependency issues, majority of them were depreciated:
lodash
gulp-minifyhtml
npmconf

please provide a quick solution to these issues:)

**Comment by ozasadnyy** [comment]
Hello, @envy7 . You don't have python installed.
I will update dependencies soon.

**Comment by ozasadnyy** [comment]
So, bower.json has been updated. I have installed everything without problems. Please, install Python and try again. Let me know if it works for you.

**Comment by ozasadnyy** [comment]
Close for now
