### ISSUE TITLE
Links in the starter-kit-plus main menu

### ISSUE THREAD

**Issue by tomasite** [gdg-x/hoverboard#29]
Hello,

I noticed a strange behavior while browsing the site through the main menu in the starter-kit branch. When you click exactly on the menu link (eg. Blog) you are correctly redirected to the page and the route in the navigation bar change properly as well. On the contrary if you click just under the link then (but on the menu item anyway) the page is well updated but not the navigation bar (eg. /blog is still displayed while we are back on home page for instance).
In order to fix it, I tried to set the anchor height to 100% which works well but I'm not sure this is the proper solution (since it's not really elegant nor fixing the problem horizontally).

Thanks for your awesome work btw,
Thomas

**Comment by ozasadnyy** [comment]
For now I have applied your suggestion. I will think how to make it better.
