### ISSUE TITLE
default-firebase-data.json is not in the repository

### ISSUE THREAD

**Issue by iblancasa** [gdg-x/hoverboard#294]
In this file: https://github.com/gdg-x/hoverboard/blob/master/docs/tutorials/firebase.md the repository references to a file called "default-firebase-data.json".

## Expected outcome

The file should be in the repository.

## Actual outcome

The files does not exists.

## Steps to reproduce

Click the link to go to the file.

**Comment by verajuhasz** [comment]
Hello,
I experiencing the same problem and I'm actually in need for help. Is there anyone already managed to setup a page using hoverboard and can aswer me these questions:
- ticket information is not visible, however I added all the info to "default-firabase-data.json" file
- same goes for the speakers 
Thanks a lot

**Comment by ozasadnyy** [comment]
@iblancasa it was in https://github.com/gdg-x/hoverboard/tree/master/docs 
In docs, there was the wrong link, thanks for pointing out!

**Comment by ozasadnyy** [comment]
@verajuhasz have you imported this json in your Firebase project?
