### ISSUE TITLE
Speaking and Schedule pages

### ISSUE THREAD

**Issue by uguruigwe** [gdg-x/hoverboard#306]
Hi,

I need assistance on where to access the speakers and schedules page data. 

I need to upload our own speakers and schedules but this has been challenging since I could not trace the source of the data locally. Guess its online.

Please, I need to fix my pages and really need direction on how to go about that.

Thank you

**Comment by uguruigwe** [comment]
Simply need to add out rockstar speakers info but can't because I could not trace the current data.

Same to the schedule page. 
Thanks

**Comment by cliveb** [comment]
Hey,

The *.json files list the files paths to speakers and schedules. After you
have deployed your own instance on Firebase server search locally for
following pages.

https://github.com/gdg-x/hoverboard/blob/master/polymer.json

"src/pages/blog-list.html",
"src/pages/blog-page.html",
"src/pages/cod-page.html",
"src/pages/post-page.html",
"src/pages/schedule-page.html",
"src/pages/speakers-page.html",
"src/pages/team-page.html"

**Comment by uguruigwe** [comment]
I got a mail to this. Please, I did not really get that.

On the speaker-page the speakers info is what I want to access and add to my own speakers.

Do I need to deploy on firebase first to access the file required for that?

**Comment by cliveb** [comment]
No, you don't need to deploy on Firebase first, but doing so first will
simplify your navigation.

**Comment by ozasadnyy** [comment]
@uguruigwe please set up Firebase application according to docs https://github.com/gdg-x/hoverboard/blob/master/docs/tutorials/firebase.md
After that, you will have data in Firebase db which you can update with your information

**Comment by uguruigwe** [comment]
Okay.

I will work it out.

I will inform you once I fix it.

Thank you.

**Comment by uguruigwe** [comment]
Thanks ozasadnyy!

Now I got it. Done what you stated.

I have done the setup of firebase as recommended.

I have imported the database (the Jason file)
I can view and edit it on my firebase database dashboard.

It is not synchronizing with the site (the speakers images are not showing up)

I have added the snippet to my data/hoverboard.config.json

Why not working yet!

Please need your assistance.

**Comment by ozasadnyy** [comment]
@uguruigwe please check path to images you set in Firebase db and if images exist there.

**Comment by uguruigwe** [comment]
Yes they do.
I imported the default database json in the doc folder.

Not just the images but the information too.

I have cross checked my path on the hoverboard.config.json file at the firebase details session it seem correct.

The name, domain, database, api, etc

Let me not bother you much.
Do you think there is something I missed?

If no, let me play around it and fix it.

I appreciate a lot.

Hope to resolve and thank you more @ozasadnyy

**Comment by uguruigwe** [comment]
I meant it is not only the images that are not showing but the entire information form the database created.

I am doubting if the the firebase db is synchronizing with the app well

**Comment by ozasadnyy** [comment]
@uguruigwe please give a link to the website and repo

**Comment by uguruigwe** [comment]
Thanks all. I have fixed it.

I have to set the authentication from the database rule.

I appreciate and especially my friend @ozasadnyy

**Comment by uguruigwe** [comment]
Okay. I will
