### ISSUE TITLE
v2: Schedule doesn't display with default data

### ISSUE THREAD

**Issue by dbs** [gdg-x/hoverboard#307]
Trying out hoverboard-v2 and using the current [default data](https://github.com/gdg-x/hoverboard/blob/hoverboard-v2/docs/default-firabase-data.json) for the Firebase database in hoverboard-v2, I receive the following error when trying to view the schedule:

    TypeError: timeslot.sessions[sessionIndex].items is undefined  schedule-webworker.js:69:39

This reference corresponds to the following line in the service worker:

    for (let subSessionIndex = 0, subSessionsLen = timeslot.sessions[sessionIndex].items.length; subSessionIndex < subSessionsLen; subSessionIndex++) {

**Comment by ozasadnyy** [comment]
@dbs docs haven't been updated for v2. We don't want to release it until we finalize the db scheme

**Comment by dbs** [comment]
@ozasadnyy I realize it's a branch for future development, but normally projects keep their branches in working order. If the default data doesn't work with the service worker in the v2 branch, that's a hurdle for enabling others to contribute towards the development of v2.

I don't think anyone would be surprised if the db schema changes as the code continues to develop. It seems like it would be a good idea to get it back to a working state, first, and then evolve from there.

**Comment by dbs** [comment]
For those following along at home, to use the current schedule-webworker.js in hoverboard-v2, the default-firebase-data.json file needs to be adjusted to list the session IDs in an array of the `items` key inside the "schedule" block like so:

    "schedule" : [ {
      "date" : "2017-11-04",
      "dateReadable" : "November 4",
      "timeslots" : [ {
        "endTime" : "10:00",
        "sessions" : [ {
          "items": [ 100 ]
        } ],
        "startTime" : "09:00"
      }, {
        "endTime" : "11:00",
        "sessions" : [ {
          "items": [ 101 ]
        } ],
        "startTime" : "10:00"
      } ],

**Comment by ozasadnyy** [comment]
@dbs you right and sorry for not doing so. We will start on documentation ASAP.
Your scheme is correct. In addition to this, you can extend session slot for several timeslots. To enable it, just add `extend` property to items in `sessions` array:
```js
"sessions" : [ {
      "extend": 2,
      "items": [ 100 ]
} ]
```
This means that session block `[100]` will be from "09:00" until "11:00". It makes sense when you have several tracks and, for instance, one of them is workshop steam where one session lasts for 2-3 of regular one

**Comment by ozasadnyy** [comment]
We have finalized data structure and updated JSON with the default data.
