### ISSUE TITLE
Agenda items and speakers are not being displayed.

### ISSUE THREAD

**Issue by resand** [gdg-x/hoverboard#3114]
**Describe the bug**

Agenda items and speakers are not being displayed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abraham** [comment]
We're unable to help if you do not provide any details. If you are still having issues please open a new issue and fill out the template.
