### ISSUE TITLE
Blank page with the event title displayed

### ISSUE THREAD

**Issue by sownt** [gdg-x/hoverboard#3150]
**Describe the bug**
After following the tutorial I just get a blank page with the event title displayed. The other parts don't work, can someone show me how to run this page?

**Screenshots**
![Screenshot 2024-09-19 at 02 45 06](https://github.com/user-attachments/assets/b3de1a2b-35e0-4f12-8d5d-e25e9d5431cb)

**Comment by abraham** [comment]
Either the browser developer tools or the terminal where you ran the start command should include some errors.
