### ISSUE TITLE
[urgent help] - what version of polymer works with (last release) v1.2.0?

### ISSUE THREAD

**Issue by cliveb** [gdg-x/hoverboard#319]
Can anyone recommend a version of polymer-cli that works with Hoverboard v1.2.0?
https://www.polymer-project.org/1.0/docs/release-notes.html 

We are using the last release of Hoverboard v1.2.0  https://github.com/gdg-x/hoverboard/tree/v1.2.0 

Last year I deployed Hoverboard using 

npm i -g polymer-cli@0.12.0
npm i -g bower

This year my project has many polymer parser.pp$3.parse errors after Unable to uglify warnings using polymer-cli@0.12.0

https://www.polymer-project.org/1.0/docs/release-notes.html 

My npm 5.3.0
My node v8.4.0
My polymer --version 0.12.0

Here is my master if helps 
https://github.com/cliveb/hoverboard/tree/master 
Thanks
clive @ Seattle GDG

**Comment by ozasadnyy** [comment]
@cliveb `polymer-cli` does not affect hoverboard as it's using custom build with `polymer-build`

**Comment by cliveb** [comment]
@ozasadnyy Any ideas why custom build with polymer-build is not building. I've tried everything I can think of? https://github.com/cliveb/hoverboard/tree/master

**Comment by cliveb** [comment]
We created a staging site using Docker, not working either may be v1.2.0 is bad? 
https://devfest-5e732.firebaseapp.com/

**Comment by ozasadnyy** [comment]
Probably yes, I am familiar with Docker, it was added by the community. Checking your site locally

**Comment by ozasadnyy** [comment]
So yes, just use `gulp` to build the project. To make it automatically and deploy on the hosting, consider using Travis: https://github.com/gdg-x/hoverboard/blob/master/docs/tutorials/deploy.md
