### ISSUE TITLE
v2 Schedule with more than 3 tracks

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#321]
Our DevFest is 1 day but notorius to have 6 tracks (or more).
Right now `schedule-day.html` is geared for 3 tracks (https://github.com/gdg-x/hoverboard/blob/hoverboard-v2/src/elements/schedule-day.html#L46 `grid-template-columns: repeat(3, 1fr);`). With this the 4-6 track came out in variable sizes. The quick fix for me is to hard-wire 6 there. I wonder if there's a way to automate, technically in JS we have in some places `day.tracks.length`, but I don't know how to interpolate this to the CSS section. We don't have nunchuks now right?

The other UX issue with 6 tracks is that each column is narrow. I'll try to override `--max-container-width` just for that page.

**Comment by lacolaco** [comment]
Maybe, we (DevFest Tokyo) will be in the same situation.
We'll also have 6+ tracks. At last year, we customized hoverboard-v1. https://tokyo.gdgjapan.org/schedule/day1
Narrow columns are not beautiful but it's not an important issue. It is important to be able to customize easily. 
Thanks.

**Comment by MrCsabaToth** [comment]
You can see previous years' Valley DevFests. I customized v2 in 2017 and v1 in 2016 and 2015

**Comment by lacolaco** [comment]
@MrCsabaToth Thank you for the information!

**Comment by ozasadnyy** [comment]
@MrCsabaToth , @lacolaco we remember about this issue ;)
Right now we are moving from RT Database to Firestore and changing schedule scheme. So this page will be updated according to it with the support of dynamic schedule tracks.

**Comment by MrCsabaToth** [comment]
Will there be any session based on Hoverboard during Global Summit? Or GDG-X session.
Will you come?

**Comment by ozasadnyy** [comment]
@MrCsabaToth I have applied to speak but didn't get any confirmation yet. But yeah, I will be there so we can discuss Hoverboard.

**Comment by ozasadnyy** [comment]
Fixed in #459
