### ISSUE TITLE
v1.2.0 buy button does not buy ticket: How to handle?

### ISSUE THREAD

**Issue by cliveb** [gdg-x/hoverboard#322]
Buy button on toolbar does not navigate to tickets. What will be acceptable pull request accepted by maintainers? 

Buy button on header-content scrolls to tickets (beautifully implemented). Tool bar is commonly used across Home, Schedule, Speakers, Team (not implemented). What is the best way to fix the Buy button on tool bar to navigate to tickets?

https://github.com/GDGSeattle/hoverboard/blob/develop/src/elements/toolbar-block.html
   </paper-menu-button>

        <div class="action-button-wrapper" hidden$="[[app.isPhoneSize]]" layout horizontal center-center>
          <a href="{$ tickets.url $}" target="_blank" rel="noopener noreferrer" on-tap="_trackBuyClick">
            <paper-button class="action-button">{$ buyTicket $}</paper-button>

https://github.com/GDGSeattle/hoverboard/blob/develop/src/elements/header-content.html

   </div>
              <div class="action-buttons">
                <paper-button class="primary" on-tap="_scrollToTickets" raised>{$ buyTicket $}</paper-button>
              </div>

**Comment by cliveb** [comment]
@ozasadnyy Any chance you can give me some direction here. I can't figure out what the maintainers intended. Is this bug on experimental firebase functionality?

**Comment by ozasadnyy** [comment]
@cliveb to achieve the expected result you have to switch the page to "home" and invoke the scroll function as it is done in the Hero.
