### ISSUE TITLE
v1.2.0 help? Does anyone have Firebase schedule, sessions, speakers working? 

### ISSUE THREAD

**Issue by cliveb** [gdg-x/hoverboard#333]
Does anyone have Firebase schedule, sessions, speakers working for DevFest 2017 using Hoverboard master I can look at?

Appears maintainers removed a key on speakers.json. I can't quite figure out. When I add it everything related stops working 

https://github.com/gdg-x/hoverboard/tree/v1.2.0

**Comment by cliveb** [comment]
@cliveb Study this: https://github.com/IWDC2017/WTM2017/tree/develop/data
@cliveb I keep the JSON data in the source repo. Do you have a link?
@cliveb Your speakers, sessions and schedule JSON section has to be in concert with each other. Also make sure that you define the tracks and time slots properly...

**Comment by cliveb** [comment]
@MrCsabaToth something different and wrong with my speakers json I have null, you have keys? GDGSeattle/hoverboard@0268985
If I export speakers and fix null, everything breaks. My work around is edit slowly in Firebase.

**Comment by cliveb** [comment]
Ready for DevFest Seattle tomorrow https://devfestseattle.org/ I avoided trying to fix nulls and missing keys in speakers.json. Something went wrong merging versions. Don't do this (duh).

I think master project json on speakers is bad json (watch out!!).

**Comment by MrCsabaToth** [comment]
I didn't see any nulls

**Comment by cliveb** [comment]
@MrCsabaToth nulls nearly killed me. 

![nulls2017-10-06_1751](https://user-images.githubusercontent.com/733870/31303263-4fdd59c6-aabf-11e7-825f-7ad092644078.png)

**Comment by MrCsabaToth** [comment]
You have 3 tracks, so your session type time slots should reference 3 sessions like [ [track1_sess1id], [track2_sess1id], [track3_sess1id] ].

**Comment by cliveb** [comment]
Arggg. Thanks.

**Comment by MrCsabaToth** [comment]
What are those nulls? Why are they there? Once again, I can only refer my data.

**Comment by cliveb** [comment]
Export my speakers.json from Firebase and I still have the nulls shown above. If I fix them (like a good dev) locally and reload. My speakers, schedule, sessions stop working. 

My speakers from last year has id's not nulls. I am lost why other than leaving a note here in case others trip over same issue.

My site is working for tomorrow. I can sleep.
![2016-had-keys-no-nulls-2017-10-06_1807](https://user-images.githubusercontent.com/733870/31303416-13a0ebe6-aac2-11e7-8a16-7fb632408eb0.png)
