### ISSUE TITLE
v2 doesnt work on IE 10 / Edge styles are broken

### ISSUE THREAD

**Issue by echoAlexey** [gdg-x/hoverboard#354]

**Comment by ozasadnyy** [comment]
@echoAlexey thanks for the report. We are not going to support IE any version but will try to fix on Edge.
Any PR is appreciated :)

**Comment by anxolerd** [comment]
@echoAlexey Can you please provide the following information:

- url of page on which styles are broken
- version of Edge/EdgeHTML
- screenshot of broken styles

I've briefly checked all main pages (home, speakers, schedule, team, blog) in Edge (Microsoft Edge 41.16299.15.0/Microsoft EdgeHTML 16.16299) and haven't noticed anything suspicious.

**Comment by echoAlexey** [comment]
I use browser stack to check.
Edge 14 is broken. Schedule, Sessions, Home.
Screenshots below:

![selection_013](https://user-images.githubusercontent.com/3122131/35504652-4899c37a-04ec-11e8-8068-259d50245c35.png)
![selection_012](https://user-images.githubusercontent.com/3122131/35504653-48bc6650-04ec-11e8-89e7-902cf9b05f17.png)
![selection_011](https://user-images.githubusercontent.com/3122131/35504654-48da9576-04ec-11e8-89b3-bc75186f6d4b.png)

**Comment by sophieH29** [comment]
@echoAlexey I've checked on Edge, everything looks fine. I've got version 17.17134. Can you upgrade your browser?
