### ISSUE TITLE
make the site multilingual

### ISSUE THREAD

**Issue by smaillns** [gdg-x/hoverboard#355]
is there an easy way to make the site multilingual ? thx

**Comment by cliveb** [comment]
@smaillns  Browser based multilingual. Site already supports UK (Ukraine) home language of the authors. Follow UK folder structure and add additional languages with image files and any other content not browser based multilingual.

**Comment by ozasadnyy** [comment]
@smaillns not really, it was possible in the previous version as @cliveb mentioned but then we removed for the performance purposes. We will take a count this feature in next releases.

**Comment by ozasadnyy** [comment]
Related to the old app. Please follow the #454 for the feature updates in the current release
