### ISSUE TITLE
Add support for hero buttons on the main page. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hoverboard#36]
The new template looks really good but I think there should be 2 options for the main page

- With video to show the website after the event has ended. 
- Before event with info and hero buttons. 

Hero buttons like REGISTER, SPEAKER APPLY are really important.

**Comment by ozasadnyy** [comment]
I am not sure what you mean in the first statement..
About second I will do it in the next milestone

**Comment by tasomaniac** [comment]
I meant the current version with youtube video on the hero. I think there can be 2 options.

**Comment by ozasadnyy** [comment]
Fixed in #55
