### ISSUE TITLE
When using serve, changes to metadata files are not reflected automatically. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hoverboard#37]
Since they are used once, changes are not detected automatically. 

Everytime I make a change, I close the browser tab, kill gulp serve and re-run it. It is not a big deal but can be improved.

**Comment by ozasadnyy** [comment]
After #100 project uses Polymer-CLI. 
Note! On file changes you have to reload page manually.

**Comment by tasomaniac** [comment]
That is fine :) Just refreshing applies the changes. It is really cool.
