### ISSUE TITLE
v2: Documentation - icons for badges

### ISSUE THREAD

**Issue by echoAlexey** [gdg-x/hoverboard#375]
At the moment icons for badges are defined in SVG.

It is hard to understand how to design similar quality icons so it can be supported for other type of badges (e.g. Java Champion, Oracle ACE, MVP)

It would be nice to have guidelines in documentation (e.g. viewbox size, colors. format of svg code etc) to pass to designer

**Comment by ozasadnyy** [comment]
In most cases, we copying icons from https://materialdesignicons.com/
They have the same 24px viewport, so it works. In another case, you can use https://icomoon.io/ to edit icons.
We will update docs closer to the release

**Comment by echoAlexey** [comment]
Hi Oleh,
Thanks!
