### ISSUE TITLE
Only 1 Free ticket looks ugly

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hoverboard#38]
The template is great if the event has multiple tickets with various prices. 

But when the event is completely free, the template looks bad. 

Something like Zeppelin's ticket component would be ok. What do you think?

![image](https://cloud.githubusercontent.com/assets/763339/13732706/836b0376-e980-11e5-8ad1-7f8a2f813507.png)

**Comment by ozasadnyy** [comment]
I would better create a new component for that with a completely new design (material design).

**Comment by tasomaniac** [comment]
Actually yes. I think we can have 2 components for 2 situations. 

One is if  the event is free and only one ticket without price. 
The other is if the event has tickets with different prices.

**Comment by ozasadnyy** [comment]
Added new design. Currently in develop branch. Will be merged in next release.

**Comment by ozasadnyy** [comment]
![resizer google design](https://cloud.githubusercontent.com/assets/2954281/14420418/ab63d42e-ffd4-11e5-98a3-0371b8acc64d.png)

[Live demo](https://hoverboard-dev.firebaseapp.com/)

Just saw that I haven't added currency glyphs to the font.
