### ISSUE TITLE
v2: header sometimes freezes and blocks content partially

### ISSUE THREAD

**Issue by echoAlexey** [gdg-x/hoverboard#387]
Sometimes hero block (head image, speakers, schedule, etc.) is frozen and content below it is partially hidden. Scrolling up and down is not helping, as hero block is not hiding. 

![selection_011](https://user-images.githubusercontent.com/3122131/35377614-907e5818-01b8-11e8-826d-9334437ac92c.png) 

Refresh helps, but it is possible to face this issue during surfing web page.

**Comment by ozasadnyy** [comment]
@echoAlexey please give details about your system and browser. Link to deployed app will be useful

**Comment by echoAlexey** [comment]
This issue is seen on multiple systems.
- Linux, Ubuntu, Chrome Version 63.0.3239.108 (Official Build) (64-bit)
- OS X, Chrome Version 63.0.3239.132 (64-bit) 

https://rigadevdays.lv/

**Comment by ozasadnyy** [comment]
Should be fixed in #404 . 
Please reopen if you still see the issue
