### ISSUE TITLE
v2: allow to customize meta tags

### ISSUE THREAD

**Issue by echoAlexey** [gdg-x/hoverboard#399]
It would be great if depending on a page meta-tags could be customized.

Use cases: load blog post summary / speaker short bio when URL for speaker/blog post is shared.

**Comment by ozasadnyy** [comment]
We can create something like that to change meta tags in a header, but, for instance, facebook will not retrieve this data. For such purpose, we need to implement SSR (which probably can be done with Firebase functions and Puppeteer)

**Comment by ozasadnyy** [comment]
Fixed in #432
