### ISSUE TITLE
Twitter previews card are missing the `social_share` image for all the URLs

### ISSUE THREAD

**Issue by cortinico** [gdg-x/hoverboard#402]
Looks like the pages from any hoverboard website are missing the `social_share` image when shared on twitter.

## Expected outcome

All the pages should provide the `social_share` image as a preview.

## Actual outcome

All the pages are missing the preview image.

## Steps to reproduce

1. Open the [twitter card validator](https://cards-dev.twitter.com/validator)
2. Test the following url: [https://hoverboard-master.firebaseapp.com/](https://hoverboard-master.firebaseapp.com/)
3. The preview will have no image.
![Imgur](https://i.imgur.com/GhsaB82.png)

**Comment by ozasadnyy** [comment]
Fixed in #403
