### ISSUE TITLE
v2 can be used or not ?

### ISSUE THREAD

**Issue by davinkevin** [gdg-x/hoverboard#417]
Hi, 

We are planning to start the website of the Devfest Toulouse and we would like to know if the branch dedicated to the future v2 is "production ready". I think you used it for your event last year, so I think we can use it for our event which is planned for November. 

Thanks for your feedback

**Comment by ozasadnyy** [comment]
@davinkevin it is not polished well + we have plans for migration to Firestore and Polymer 3.
In any case, we are using it at GDG DevFest Ukraine https://devfest.gdg.org.ua/ and you can, but be ready for breakable changes.

**Comment by davinkevin** [comment]
Right now, the version on `hoverboard-v2` is working... so even if you are doing major breaking change between now and November, we can decide to not update our fork and stay on a specific version...

Do you have an idea of when you will release it? I don't find any milestone about it...

**Comment by cliveb** [comment]
Salute plans for migration to Firestone and Polymer 3 (and ES6 modules). I'd also like to see hoverboard-v2 release and its doc set maintained. Since many small changes from hoverboard-v1 are encapsulated in 'v2' that throw newbs who implement PWA but don't develop actually develop javascript. Rather than the doc represent latest Hoverboard toward v3.

**Comment by ozasadnyy** [comment]
@davinkevin plan is to release the new version before Google I/O, but it really depends how well will be a transition to Polymer v3.
@cliveb we have a task for documentation but we don't want to write it until we have the final release.

**Comment by davinkevin** [comment]
Before the IO seems good for us. Our event are planned for November, so we will have time to handle the migration...

BTW, I work with @ilaborie this year on the website, so we will decide together if we choose the v1 and v2... 

Thanks for the answers. I can close the issue 👍

**Comment by ozasadnyy** [comment]
@davinkevin I would recommend going with v2, as we will not have resources to support v1. Furthermore, v1 is using Polymer 1 with old web standards which are already supported natively from v2/v3

**Comment by ozasadnyy** [comment]
If more people will use v2, find bugs and fix them - we would have much better product from which everybody will get a benefit.

**Comment by davinkevin** [comment]
That my point of view too... using the v2 and helping to improve it like we did last year with the previous version 👍
