### ISSUE TITLE
Some items are not loading

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hoverboard#42]
As can be seen in the screenshots below, here are the problems: 

- Video section always show the same thumbnails.
- Rockstar speakers part is empty. 
- Photos section shows empty photos.

Opening the page in Incognito mode fixed it. But I've opened the page normally in Chrome about 10+ times. It didn't occur to me that I should clear the cache. 

![screen shot 2016-03-14 at 21 46 35](https://cloud.githubusercontent.com/assets/763339/13761073/5556b5b2-ea2e-11e5-8ebb-febca0e317f4.png)
![screen shot 2016-03-14 at 21 46 46](https://cloud.githubusercontent.com/assets/763339/13761072/54daa88c-ea2e-11e5-99d2-9eae48d40314.png)

**Comment by ozasadnyy** [comment]
Could you show me console logs?

**Comment by tasomaniac** [comment]
Oh I already cleared the cache and force reload the page. When I did that, I got the message saying that "Cache is complete. The app will work offline" and then it started working as expected. 

Btw, I've load the website days ago before you released it today.

**Comment by ozasadnyy** [comment]
Ok. Let's look how it will be working with next updates

**Comment by tasomaniac** [comment]
Logs are attached. 

[hoverboard.firebaseapp.com-1457993000469.txt](https://github.com/gdg-x/hoverboard/files/172932/hoverboard.firebaseapp.com-1457993000469.txt)

**Comment by ozasadnyy** [comment]
Fixed with #100
