### ISSUE TITLE
[v2] Information about the model of data for the blog

### ISSUE THREAD

**Issue by davinkevin** [gdg-x/hoverboard#424]
Hi, 

We are setting up the blog part for the DevFest Toulouse, but we don't find any information on how to organize information inside the firebase database (which is now used instead of static file in v2).

In the `/docs/default-firabase-data.json`, I don't find any entry about the blog, and especially for `/blog/list` used https://github.com/GDGToulouse/site-devfest-toulouse-2018/blob/ea95d407b3b3e7ce211e0c741f4a75fbd4b89d32/scripts/redux/actions.js#L130

Thanks for your help !

Kevin

**Comment by sophieH29** [comment]
Hi @davinkevin, sorry for that. We gonna move soon to Firestore, and our DB scheme will change a lot.
Meanwhile, I've updated default JSON with current valid data
https://github.com/gdg-x/hoverboard/blob/hoverboard-v2/docs/default-firabase-data.json
