### ISSUE TITLE
Find an alternative to Picasa Web Albums API

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hoverboard#43]
Should this be done? The experience without leaving the website was much better. 

I wonder how Google I/O website is doing right now? 
They have something like that here for example. https://events.google.com/io2015/offsite

**Comment by cliveb** [comment]
Camlistore will use Google drive api for photos. https://godoc.org/google.golang.org/api/drive/v3

**Comment by ozasadnyy** [comment]
we have to do it manually
