### ISSUE TITLE
Make it works on GitHub Pages (add base url support)

### ISSUE THREAD

**Issue by ozasadnyy** [gdg-x/hoverboard#44]
So basically, we should add support of baseurl. [Jekyll is a good example](https://jekyllrb.com/docs/configuration/#serve-command-options) how it should work.

**Comment by nicobytes** [comment]
Hi, in the moment in Bogotá, Colombia GDG Bogota we will organize a DevFest (http://devfest.gdgbogota.com/) with GitPages, but the subpages like http://devfest.gdgbogota.com/blog/ not work!!

**Comment by ozasadnyy** [comment]
Hey @nicobytes , here is information from `app-router` blog post

> Notice however that if you open the demo in its own window and change the path, refreshing will give you a 404. That's because the server doesn't know what file to serve out for that new URL!

> Helpfully, <app-location> provides the use-hash-as-path option, which will place the route path in the #hash portion of the URL. All modern browsers (IE ≥10) support routing in either the pathname or the hash but search engines prefer pathname. So you should only use-hash-as-path when you don't control the server (e.g. github pages, jsbin, or demo pages like this one that need to work with any server). Fortunately, everything else works identically either way.

Try to add `use-hash-as-path` to [app-location](https://github.com/gdg-x/hoverboard/blob/master/src/hoverboard-app.html#L104) element or consider using Firebase hosting instead which provides SSL certificate for free which gives you advantage of modern web technologies as Service worker.

**Comment by MrCsabaToth** [comment]
@ozasadnyy I experienced hosting problems with Firebase while trying to get the VRView part (only present in my fork) working. I wonder what I loose if I abandon Firebase? You mention service worker functionality. I thought that it's a client side functionality and the website content can be served as static website.

@nicobytes What is sure is that if you serve it from `gh-pages`, GitHub won't provide HTTPS in case you have a custom domain (like us too). One solution is to set up free CloudFlare service:

See:
* https://robinwinslow.uk/2016/02/13/free-https-custom-hosting/
* https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/
* https://www.tddapps.com/2015/09/08/Custom-Domain-on-GitHub-Pages/
* https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

I do not want to advocate against Firebase at all. I wonder though others' experience with CloudFlare

**Comment by tasomaniac** [comment]
I think ideally hoverboard project should provide alternatives. `gh-pages` is a very good and fully free alternative. Just someone should work on it to support it. I think it is not that hard. 

`gh-pages` unfortunately does not support SSL as you said. This disables service worker functionality. An easy (and maybe the only) way to overcome this to use Cloudflare. We did that for Devfest Istanbul last year. It was working pretty good. I would recommend it.

**Comment by MrCsabaToth** [comment]
Actually, I realized not so long ago that subpages don't work for me (with gh-pages + ClodFlare). CloudFlare does provide SSL for my custom domain. When I navigate to a subpage and try to reload, or share a subpage URL:
![ghpages_cloudflare_subdomain](https://cloud.githubusercontent.com/assets/744949/18805592/d7e50d50-81c6-11e6-96fd-a574746486df.png)

I was thinking: something is wrong with the routing itself within the PWA. But then why would this work well with the Firebase hosting?

**Comment by MrCsabaToth** [comment]
I'm considering moving back to Firebase, but then I have to abandon the cool VRView component I developed

**Comment by MrCsabaToth** [comment]
https://hoverboard.firebaseapp.com/schedule/day1 from a virgin browser's private mode works, but https://valleydevfest.com/schedule/day1 does not

**Comment by ozasadnyy** [comment]
@MrCsabaToth maybe it's rewrites? https://firebase.google.com/docs/hosting/full-config
```
When to use a rewrite: Use a rewrite when you want to show the same content for multiple URLs. Rewrites are particularly useful with pattern matching, as you can accept any URL that matches the pattern and let the client-side code decide what to display.
```

**Comment by MrCsabaToth** [comment]
So only those hosting solutions qualify for handling "non root" URLs who can do such rewrite? Makes sense, because if the provider is really just a static website provider and you hit it with a /schedule/day1 path, the server clearly won't find that path. This is actually I believe a general problem for SPAs, and I quite frankly don't understand how it'd be done without such rewrite. We use `<app-route>` for routing, Once the web app is cached, is the system intelligent enough that it somehow magically it'd operate and sort out things before requests actually would reach the server (like in off-line mode)?

**Comment by ozasadnyy** [comment]
In this case, it's better to use hash as path
https://github.com/PolymerElements/app-route#hashes-vs-paths

**Comment by vorcigernix** [comment]
I tried to add use-hash-as-path to <app-location> and the whole site does not work anymore. It is probably because some basic routes are defined as paths, but I can't find where to change them and how. Anyone can point me to right file?

**Comment by tasomaniac** [comment]
After having problems with Firebase, we did the same for https://devfest.istanbul with CloudFlare universal SSL. 
We also have the path links giving 404 problem but we are living with it. 

My very basic solution to deploy github pages is to copy the build folder to `docs` folder manually. Now github pages deploy the webpage in `docs` folder in `master` branch. 

How did you guys do it?

**Comment by ozasadnyy** [comment]
@tasomaniac, Which problems did you have with Firebase?

**Comment by tasomaniac** [comment]
Custom domain was stuck on SSL certificate. After 5 days the website still didn't have the right certificate. And there is no way to change anything regarding to that. Firebase is all automatic and good. But it is the worst when it doesn't work automatically. They were redirecting to https eventhough the certificate is not valid.
