### ISSUE TITLE
Deploy on firebase doesn't change content

### ISSUE THREAD

**Issue by Nuruddinjr** [gdg-x/hoverboard#446]
I am running `firebase deploy` or `yarn deploy` both says deploy complete without a problem, but content doesn't change on Firebase. I tried to open other browsers and incognito. Still no change.

**Comment by ozasadnyy** [comment]
Are you checking website defined in https://github.com/gdg-x/hoverboard/blob/hoverboard-v2/config/development.json ?

**Comment by ozasadnyy** [comment]
Also, have you ran `yarn build` before?

**Comment by Nuruddinjr** [comment]
Yeah checking development url, but I haven't run `yarn build'` shouldn't yarn deploy do this ?

**Comment by ozasadnyy** [comment]
No, `deploy` is only deploying. You have to run `build` before.

**Comment by Nuruddinjr** [comment]
@ozasadnyy when content is updated?, I build and deployed, but content doesn't change if it was cached before

**Comment by ozasadnyy** [comment]
When you change content ballon in the left bottom edge of the screen should appear with prompt to refresh the page.

**Comment by Nuruddinjr** [comment]
I don't get it. When we deployed hoverboard v1, it was the same, we would't get it for a long time. I am changing some photos for example.

**Comment by sophieH29** [comment]
Hey @Nuruddinjr,  are you using v1 or v2? Didn't get from the context.
If you use hoverboard-v2, have you done these steps?
1. update configs to your DB in  https://github.com/gdg-x/hoverboard/blob/hoverboard-v2/config/development.json
2. run  "yarn build" 
3. run "yarn deploy"
4. go to the website specified in development.json config. On the bottom left should appear toast to refresh the page, to get the new content. If it hasn't appeared (what supposed to be) you can trigger changes in a harder way by clearing cache and hard reload.

**Comment by Nuruddinjr** [comment]
@sophieH29 I am using v2. I am not getting toast bar to update, no one else in my team also.

**Comment by sophieH29** [comment]
but you ran all of those steps, right? Haven't you tried cache reset and hard reload at least? If it wouldn't help to see updated content, that means something wrong with your deployment

**Comment by Nuruddinjr** [comment]
I tried cache restart, delete application data ,then new version comes to life. But, not all of our users will be able too see new version.
