### ISSUE TITLE
Create a skeleton to support Progressive Web Apps

### ISSUE THREAD

**Issue by ozasadnyy** [gdg-x/hoverboard#45]
* [Getting started with Progressive Web Apps](https://addyosmani.com/blog/getting-started-with-progressive-web-apps/)
* [Building Progressive Web Apps with Polymer (Chrome Dev Summit 2015)](https://www.youtube.com/watch?v=g7f1Az5fxgU&index=10&list=PLNYkxOF6rcICcHeQY02XLvoGL34rZFWZn)
* [polymer starter kit plus skeleton](https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/app/views/skeleton.html)

**Comment by limhenry** [comment]
how about [PRPL](https://www.polymer-project.org/1.0/toolbox/server)?

**Comment by ozasadnyy** [comment]
All of these things already developed or in progress check out [polymer-cli branch](https://github.com/gdg-x/hoverboard/tree/polymer-cli)

**Comment by ozasadnyy** [comment]
After #100 project uses PRPL pattern.
