### ISSUE TITLE
v2: "Buy Ticket" button in toolbar and link in mobile menu don't work

### ISSUE THREAD

**Issue by webmaxru** [gdg-x/hoverboard#456]
Nothing happens on the click because href refers to `tickets.url` in Firebase: `href$="[[tickets.url]]"`. But you can't add this key there  because tickets block stop working on the main page (it expects some objects)

My quick and dirty fix was to
- replace `href$="[[tickets.url]]"` with `href="{$ buyTicketUrl $}"` in `header-toolbar.html` and `hoverboard-app.html`
- add `"buyTicketUrl": "https://ti.to/mobile-era/2018/",` to `resources.json`

If you wish I could do PR with these updates. Otherwise please fix that asap - it's not cool when the main CTA button doesn't work :)

**Comment by ozasadnyy** [comment]
Fixed in #458
