### ISSUE TITLE
Add contact pages

### ISSUE THREAD

**Issue by ozasadnyy** [gdg-x/hoverboard#46]
An example [https://devfest.gdg.org.ua/2014/team/](https://devfest.gdg.org.ua/2014/team/)

**Comment by juarezpaf** [comment]
This weekend I was checking mailgun https://www.mailgun.com/pricing and it's possible to send emails via API using JavaScript. :smile:

**Comment by ozasadnyy** [comment]
I think we should make it simple as possible =)

**Comment by juarezpaf** [comment]
@ozasadnyy no contact form and instead use a `mailto:` link?

**Comment by ozasadnyy** [comment]
exactly. Contact form can be made additionally afterwards
