### ISSUE TITLE
v2: Crashes (Mobile-) Safari

### ISSUE THREAD

**Issue by caffeineflo** [gdg-x/hoverboard#460]
Crash, reload, crash reload, then error page from Safari (see screenshot).

Can't give you debug information as debugger crashes too. Happens on macOS 10.13.5 Safari 11.1.1 and iOS 11.4.1.

<img width="377" alt="screen shot 2018-07-03 at 09 05 41" src="https://user-images.githubusercontent.com/1525283/42221529-50f58bf2-7ea0-11e8-8fca-f1f92d19f9bc.png">

**Comment by ozasadnyy** [comment]
Thanks for submitting the issue. Will try to fix it ASAP.

**Comment by ozasadnyy** [comment]
It happens due to the bug in Safari 11 when it renders Google Map in shadow dom. More info here: https://stackoverflow.com/questions/50952705/google-map-markers-not-working-with-shadow-dom-in-safari/50959124#50959124

Fixed in #461
