### ISSUE TITLE
Angular framework as documentation?

### ISSUE THREAD

**Issue by cliveb** [gdg-x/hoverboard#468]
Hoverboard 2.0 has matured into a comprehensive PWA template based on PRPL pattern for DevFest season. One of the really time consuming issues deploying Hoverboard for a new GDG is learning how to customize Hoverboard beyond the metadata driven tables. Could Hoverboard benefit from commits by experts in Angular framework. Would this be counterproductive to the vision held by the Hoverboard authors? @ozasadnyy  / (@MrCsabaToth).

Asking on behalf of others
https://angular.io/

**Comment by sophieH29** [comment]
Hey @cliveb, as I understood you want to build some tool in Angular that will make life easier for people who start using Hoverboard, am I right? If yes, - it is amazing!
Can you please describe your idea in more details?

**Comment by cliveb** [comment]
Hey @cnishina, @margaretmz. Alas my cup overfloweth. Please can you help connect who has skills to backfit Hoverboard with Angular. Ty.

**Comment by MrCsabaToth** [comment]
Hoverboard can definitely benefit from contributions. Compared to DeLoeran I'd say there are two things Hoverboard can catch up: 1. administrative views to easily modify Speakers, Sponsors, Schedule through web UI. These would work on the Firebase DB, in DeLorean these extra Edit features are added on-demand to the respective views in case someone is an admin of the site. 2. Better iOS support for Polymer / PWA. This one is out of scope of Hoverboard, but lately Apple took steps towards better support of these technologies.

**Comment by muralihr** [comment]
@cliveb  hey we can try this ~ are you part of the team that built hoverboard ~ angular will make it easier and portable and also simpler to exxecute such projects is what i feel  ~ lets set up a meet up on skype ~

**Comment by muralihr** [comment]
@ozasadnyy / (@MrCsabaToth). why are we not porting to angular 7 ? the current code is little complex for beginners

**Comment by ozasadnyy** [comment]
@muralihr I don't think it's a good idea to rewrite it with different techniques using the same name. But you definitely can start a new one!

**Comment by abraham** [comment]
There are also a couple DevFests that built their own Angular sites. Those would be better options than rewriting Hoverboard.

**Comment by MrCsabaToth** [comment]
@muralihr Along @abraham 's line, we should mention https://github.com/neojato/DeLorean-v2 . I made small contributions to Hoverboard, and I made enhancements to the DeLorean as well. Looking at trends into the future, although personally I like Polymer better than Angular, it seems like a future project should be based on Angular (which in turn support web components after all). I had plans to upgrade DeLorean to Angular 7 or 8 for a long time, but as September is approaching fast I'm not sure if that will happen for this DevFest. I'm not too experienced with Angular (this branch https://github.com/CsabaConsulting/DeLorean-v2/ meant to get rid of deprecated Firebase APIs, but not finished) and an expert would have helped me. In case @muralihr you'd upgrade it to Angular 7 or 8, please factor in these features: being able to sort / group the schedule both by time, room or tracks. I added feature (priority numbers) so tracks and time slots can be explicitly ordered, ideally this should be transparent and rather taken care of by some smart listview where you can re-order by drag-and-drop. We'd need to funnel this conversation into either Slack or some gitter chat room. I'm very interested in this.

**Comment by cliveb** [comment]
Paul and Jake had a good discussion on libraries & frameworks. https://youtu.be/t_pxnrLktNI

Following their conclusions, I feel to make Polymer based Hoverboard continue for a wider GDG adoption either a framework is inevitable or more tests to act are required. i.e data discontinuity crops up team <-> speakers <-> schedule tables there is no way to catch culprit. This can occur the last minute as changes are made for live GDG events. 

It would be good to know how @aerotwist & @jaffathecake think today after seeing Polymer evolving to more complex web apps.

**Comment by abraham** [comment]
A better documentation site for Hoverboard would probably be good. Angular isn't the right tool for that though.

If anyone wants to help out there are a number of issues tagged with [help wanted](https://github.com/gdg-x/hoverboard/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).
