### ISSUE TITLE
Add possibility to create own schedule

### ISSUE THREAD

**Issue by ozasadnyy** [gdg-x/hoverboard#47]
For attendees, it would be nice to have a possibility to create their own schedule with selected sessions.

**Comment by tasomaniac** [comment]
Is this going to be stored local? Or are you going to persist it to Firebase with Google login etc?

**Comment by ozasadnyy** [comment]
@tasomaniac I am not sure, but Firebase or Google API. We need to sync it between devices.

**Comment by tasomaniac** [comment]
Nice :+1:

**Comment by juarezpaf** [comment]
I was thinking in something to generate the `json` locally, after this the user could send the commit and update the website. Another possibility is to create a config variable called `firebase_url`, check if this exist and instead of generate the json locally sync with Firebase.

**Comment by zasadnyy** [comment]
I'd say adding User Login (Google + Firebase as storage) is more strategic.
Having a different account types could be a new groundbreaking feature, e.g admin, speaker, attendee.

What you think?

**Comment by ozasadnyy** [comment]
We can also save it on Google Drive

**Comment by zasadnyy** [comment]
@ozasadnyy it requires extra permission while login, storing in Firebase do not require it.

I can prepare a document describing features and architecture for user login

**Comment by tasomaniac** [comment]
I think saving to Google Drive will be much harder. 
I don't think we would hit the storage limit of Firebase. So when you think how easy it would be, I think Firebase makes a lot of sense for this.

**Comment by tasomaniac** [comment]
And then, having an admin UI to edit the schedule would be really really easy.

**Comment by zasadnyy** [comment]
@tasomaniac we're thinking in the same direction

**Comment by juarezpaf** [comment]
@tasomaniac @zasadnyy what about offline support?

**Comment by ozasadnyy** [comment]
@juarezpaf it's easy =) We can save it locally and sync with Firebase when connection will be restored.

**Comment by zasadnyy** [comment]
No need, firebase keeps local copy of storage https://www.firebase.com/docs/web/guide/offline-capabilities.html

**Comment by ozasadnyy** [comment]
@tasomaniac admin panel will also made later

**Comment by tasomaniac** [comment]
I agree that Admin panel is out of this issue's scope. But it is related :)

**Comment by ozasadnyy** [comment]
Fixed in [v1.1.0](https://github.com/gdg-x/hoverboard/releases/tag/v1.1.0)
