### ISSUE TITLE
npm run firestore:init giving error

### ISSUE THREAD

**Issue by cleopatra27** [gdg-x/hoverboard#472]
Error: Unable to list collection IDs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hoverboard@2.0.0-alpha.1 firestore:init: `firebase firestore:delete -r --all-collections && babel-node ./internals/import-default-data`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hoverboard@2.0.0-alpha.1 firestore:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cleopatra.douglas\AppData\Roaming\npm-cache\_logs\2018-07-15T11_21_58_650Z-debug.log

**Comment by ozasadnyy** [comment]
@cleopatra27 have you enabled Firestore for the project?

**Comment by Nuruddinjr** [comment]
I also have the same issue, I enabled Firestore on my project. Here is the current view of Storage section http://take.ms/QXeRs

**Comment by Nuruddinjr** [comment]
I found Firestore under database section rather than storage, it might be confusing. I thought Firestore was enabled by seeing storage.

**Comment by cleopatra27** [comment]
Hi,

Thanks, have fixed this, same thing here....

Now trying to deply and getting this.

firebase deploy

=== Deploying to 'devfestfreetown'...

i  deploying database, firestore, functions, hosting
Running command: npm --prefix $RESOURCE_DIR run build

> hoverboard@2.0.0-alpha.1 build C:\Users\cleopatra.douglas\Desktop\DEVFESTSIERRALEONE\%RESOURCE_DIR%
> gulp

File path config/development.json selected as config...
[21:49:50] Using gulpfile ~\Desktop\DEVFESTSIERRALEONE\%RESOURCE_DIR%\gulpfile.js
[21:49:50] Starting 'default'...
[21:49:50] Starting 'lint'...
[21:49:52] Finished 'lint' after 1.58 s
[21:49:52] Starting 'build'...
Deleting build and .temp directories...
Compiling template...
Polymer building...
Analyzing and optimizing...
[21:49:53] 'build' errored after 1.13 s
[21:49:53] Error: Unable to get document .temp/src/pages/blog-list-page.html: Document not found: .temp/src/pages/blog-list-page.html
    at BuildAnalyzer.<anonymous> (C:\Users\cleopatra.douglas\Desktop\DEVFESTSIERRALEONE\%RESOURCE_DIR%\node_modules\polymer-build\lib\analyzer.js:323:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\cleopatra.douglas\Desktop\DEVFESTSIERRALEONE\%RESOURCE_DIR%\node_modules\polymer-build\lib\analyzer.js:17:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[21:49:53] 'default' errored after 2.72 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hoverboard@2.0.0-alpha.1 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hoverboard@2.0.0-alpha.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cleopatra.douglas\AppData\Roaming\npm-cache\_logs\2018-07-15T20_49_53_213Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code1

Having trouble? Try firebase deploy --help

**Comment by ozasadnyy** [comment]
@cleopatra27 can you run `yarn build` and if it would be successful - `firebase deploy`.
Did you change anything inside before the build (especially blog, looks like the problem right there)

**Comment by ozasadnyy** [comment]
@cleopatra27 any updates here?

**Comment by yong076** [comment]
@ozasadnyy Hi! I am having a lot of trouble preparing for the conference, so I tried to do it myself. FireBase Web Console -> DataBase -> FireStone. Of course I would have done it, but if someone sees the issue, I hope it helps.

**Comment by ozasadnyy** [comment]
Closing the issue. Don't forget to enable Firestore in Firebase admin

**Comment by alpha-beta-soup** [comment]
This step is not included in the README.md

**Comment by ozasadnyy** [comment]
Added to the readme file
