### ISSUE TITLE
fix(disabledSchedule): talk description has invalid speakers

### ISSUE THREAD

**Issue by davinkevin** [gdg-x/hoverboard#473]
Hi, 

After using the last improvment about `disabledSchedule` feature, I see a problem when showing the talk details: 

![image](https://user-images.githubusercontent.com/1970922/42737270-867de60e-8871-11e8-818a-9713dfcc426e.png)

For now, I've commented the section in the HTML, but all my attempt to do a PR was a faillure 😓.

From my point of view, we should `hidden$` a part of the component when the value `disabledSchedule` is to true. But I still have too many problem with `hidden$`bindings in the polymer world. 

BTW, I've tried to use the nunjucks syntax to completly remove this part of the template but this leads to compilation error... 

If you can help me about this, I still can do a PR 😎

**Comment by ozasadnyy** [comment]
hey @davinkevin , so you want to hide speakers section in sessions details? It makes sense if you have only one speaker per session but if you have more it would make much more sense to show other speakers too. Does it make sense for you?

**Comment by davinkevin** [comment]
I want to hide it because at this moment (and in my case, without schedule) the `speakers` array in sessions is composed of `string` instead object. 

So we can't show information without doing huge modification in the webworker (like proposed in a previous request, which has been closed). 

You can see it in the capture I add, the wrong circle grey should display the speaker avatar and some information, but in this case, with only string in the array, the template can't do that.

I hope this is more clear now 😊

**Comment by ozasadnyy** [comment]
This definitely a bug :) Would you like to fix them, I would guide you.
What we have to do:
* Hide text about a date, time and session track from session details: https://github.com/gdg-x/hoverboard/blob/master/src/elements/dialogs/session-details.html#L71:L72
* As we already have [speakers details map](https://github.com/gdg-x/hoverboard/blob/master/src/mixins/speakers-hoc.html#L13) we can get all needed information.
Create a function that will return an array with speakers details if you [pass array](https://github.com/gdg-x/hoverboard/blob/master/src/elements/dialogs/session-details.html#L106) of speakers ids. If it's already an array of objects, return it back (to work with `"disabledSchedule": false`)

**Comment by davinkevin** [comment]
After some reading about bindings in Polymer, I finally success to do something (I'me coming from Angular world, so I have some bad habits at few levels...)

So I've done this : https://github.com/davinkevin/hoverboard/commit/c63bfb3893c936149bfc03ebbe48a15b23278e47

I've used like you proposed the `speakersMap` element, but I'm still wondering why we aren't doing this merge operation inside the webworker. In that case, the value will always be the same in the app, with or without a schedule. 

Thanks for your help 😉
