### ISSUE TITLE
ERROR npm run firestore:init  

### ISSUE THREAD

**Issue by jocgiraldo** [gdg-x/hoverboard#481]
Error: Missing required options (confirm) while running in non-interactive mode:
- confirm You are about to delete YOUR ENTIRE DATABASE. Are you sure?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hoverboard@2.0.0 firestore:init: `firebase firestore:delete -r --all-collections && babel-node ./internals/import-default-data`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hoverboard@2.0.0 firestore:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jose\AppData\Roaming\npm-cache\_logs\2018-08-02T06_33_13_015Z-debug.log

**Comment by ozasadnyy** [comment]
@jocgiraldo Looks like it's a problem with Firebase, not Hoverboard.
Did you log in? Which version of firebase-tool have you installed?

**Comment by jocgiraldo** [comment]
The problem is git bash, the comand npm run firestore:init doesn't function. But its functions correctly in Windows CMD

**Comment by ozasadnyy** [comment]
You don't need to run in git bash. The regular console is okay. 
Closing the issue if you don't mind.
