### ISSUE TITLE
Become a partner - documentation

### ISSUE THREAD

**Issue by juliusspencer** [gdg-x/hoverboard#483]
How does the feature `Become a partner` work?

I'm not sure where to ask this question. Maybe it's a documentation issue?

Thank you!

**Comment by sophieH29** [comment]
Hello @juliusspencer,

`Become a partner` button opens a form to fill in with a company name, name and email. This data is saved into Frirestore DB, `potentialPartners` node. So that you can contact back those people who are interested to be a partner with you.

**Comment by ozasadnyy** [comment]
Fixed in #493

**Comment by nayonnapurnell** [comment]
How can we send the potentialPartner to an email instead of the database?
