### ISSUE TITLE
Hoverboard can't connect to FireStore

### ISSUE THREAD

**Issue by aayushagra** [gdg-x/hoverboard#484]
We're trying to setup HoverBoard but it's not able to pull any data from FireStore. Instead, it just leaves all the database field blank. Please see screenshots attached.

![capture](https://user-images.githubusercontent.com/4214851/43673443-01916252-97e1-11e8-8a8f-0bfa237ef647.JPG)
![capture2](https://user-images.githubusercontent.com/4214851/43673444-01c33ec6-97e1-11e8-9d76-c49310701cbe.JPG)
![capture3](https://user-images.githubusercontent.com/4214851/43673445-01f6c25a-97e1-11e8-8afe-29c7de147139.JPG)

**Comment by sophieH29** [comment]
Hello @aayushagra, I need more details on it.  Have you configured Firebase project and filled Firestore DB with data?

**Comment by aayushagra** [comment]
@sophieH29 Yes I've entered the credentials in the development.json file & Firestore DB is loaded with the data

**Comment by ozasadnyy** [comment]
@aayushagra could you give the url to your webapp?

**Comment by ozasadnyy** [comment]
@doudoujay don't make your data public :)
We have set up [Firestore rules](https://github.com/gdg-x/hoverboard/blob/master/firestore.rules) inside the project, please run `firebase deploy --only firestore:rules` from the root folder to deploy them. I will add this step to init script.
Thanks for pointing out!

**Comment by Nuruddinjr** [comment]
@aayushagra I also have the same problem, did you solve it? 
It is showing skeletons instead of data.
@ozasadnyy I tried `firebase deploy --only firestore:rules` but doesn't work. It deletes the data but doesn't import

**Comment by ozasadnyy** [comment]
@Nuruddinjr this command only deploys Firebase rules. To import data you should use `npm run firestore:init`

**Comment by Nuruddinjr** [comment]
@ozasadnyy I did `yarn firestore:init` multiple times, no result

**Comment by ozasadnyy** [comment]
@Nuruddinjr did you set the right serviceAccount?
(look at 4 https://github.com/gdg-x/hoverboard/blob/master/docs/tutorials/firebase.md)

**Comment by Nuruddinjr** [comment]
@ozasadnyy yes, it deletes my collection from firestore, but doesn't write

**Comment by ozasadnyy** [comment]
@Nuruddinjr please show your console output and validate json [file with initial data](https://github.com/gdg-x/hoverboard/blob/master/docs/default-firebase-data.json)

**Comment by ozasadnyy** [comment]
Closing for now, feel free to reopen if you still have this issue.
