### ISSUE TITLE
New Feature: Android App based on Hoverboard database 

### ISSUE THREAD

**Issue by pamuditha** [gdg-x/hoverboard#489]
The idea is to create a separate Android app then time to time we can push notifications.people can access easily their mobile phone.

check this https://github.com/CodeLanka/ezevent

**Comment by maghassan** [comment]
Wow! this is a great idea, but is it for Devfest and how can I join to participate?

**Comment by tasomaniac** [comment]
Please have a look at this issue on Squanchy. Squanchy project is used for Droidcon Italy. It has a firestore based backend. Integrating Hoverboard data with their backend will enable Squanchy app to work with Hoverboard. 

https://github.com/squanchy-dev/squanchy-firebase/issues/59

**Comment by tasomaniac** [comment]
Also please have a look at this on the Android code fore reference https://github.com/squanchy-dev/squanchy-android/issues/292

**Comment by maghassan** [comment]
Ok. If Firestore is to be used, then all this in-search features would not be possible unless we're using something like Algolia, or some cracked a way out.

**Comment by abraham** [comment]
Hoverboard should focus on providing the best PWA experience it can. If organizations want to also have native mobile app I think the next step would be to define an API in Hoverboard that apps could consume.
