### ISSUE TITLE
Find/Create service to get latest posts by hashtag from social networks

### ISSUE THREAD

**Issue by ozasadnyy** [gdg-x/hoverboard#49]
[Tweetledee](http://chrissimpkins.github.io/tweetledee/) was a solution, but it's needed a php server, parse only tweets and have limitation for requests.
It would be nice to have an API to get posts by hashtag from various social networks (g+, twitter, facebook)

**Comment by tasomaniac** [comment]
It was easy for me to put it on heroku. And we stayed in the free tier. I
can write a wiki about setting it up.

Can we use tweetledee now? I saw that you replaced it with a static json.

**Comment by ozasadnyy** [comment]
You can replace json with tweetledy If heroku provide https. I have replaced it because of CORS

**Comment by tasomaniac** [comment]
If you don't use custom domains heroku supports https by default. Since you don't need fancy domain name for tweetledee, I think it is fine and easy. 

This is used in our [WTM16 website](http://wtmistanbul.com):

https://infinite-everglades-50778.herokuapp.com/tweetledee/favoritesjson.php?c=10&cache_interval=8000

**Comment by tasomaniac** [comment]
If you are not going to do this soon, I can write a wiki post explaining how to do this with HTTPS support.

**Comment by ozasadnyy** [comment]
Create a wiki page, please.
But what about another social networks?

**Comment by tasomaniac** [comment]
For other social networks, we have to do this. 

But what is the importance of the others? In most events, including Google's events, Twitter is mostly used. 

How hard would this be? If this is hard, I think we can focus on other issues.

**Comment by ozasadnyy** [comment]
Sure it's low priority feature if Tweetledee works on heroku. But it is better to have more social streams

**Comment by mpoehler** [comment]
Another possible solution for the update tweets thing:

I use the following node script, called refreshTweets.js to update data/tweets.json (develop branch)

```
var Twit = require('twit')

var T = new Twit({
    consumer_key:         'YOUR_CONSUMER_KEY',
    consumer_secret:      'YOUR_CONSUMER_SECRET',
    access_token:         'YOUR_ACCESS_TOKEN,
    access_token_secret:  'YOUR_ACCESS_TOKEN_SECRET',
    timeout_ms:           60*1000,  // optional HTTP request timeout to apply to all requests.
});


T.get('search/tweets', { q: '#devfestHH since:2016-01-01', count: 10 }, function(err, data, response) {
    var fs = require('fs');
    fs.writeFile("data/tweets.json", JSON.stringify(data.statuses), function(err) {
        if(err) {
            return console.log(err);
        }
        console.log("The file was saved!");
    });
});
```
Where '#devfestHH' is our hashtag on twitter.
 
You need to install twit with: `npm install twit`

and then you can run `node refreshTweets.js`

**Comment by ozasadnyy** [comment]
@mpoehler it would be awesome! Also, I am still looking for @tasomaniac 's instructions how to setup Tweetledee on Heroku :)

**Comment by Splaktar** [comment]
@mpoehler thanks! That works great!

**Comment by ozasadnyy** [comment]
Updated [docs](https://github.com/gdg-x/hoverboard/blob/master/docs/tutorials/configure-app.md#tweets) with insttuctions.
