### ISSUE TITLE
Text is white n white background not rendered in firefox

### ISSUE THREAD

**Issue by yyssahn** [gdg-x/hoverboard#490]
Firefox version : 61.0.1 (64-bit)
OS : Ubuntu

https://imgur.com/G1feQ0M
As you can see, text is white with a white background

I am assuming this CSS property isn't being applied in FF
paper-button[primary][invert] {
    color: var(--default-primary-color);
    background-color: var(--text-primary-color);
}

**Comment by ozasadnyy** [comment]
Fixed in #493
