### ISSUE TITLE
mailchimp subscribe fails

### ISSUE THREAD

**Issue by lockerfish** [gdg-x/hoverboard#495]
I suspect that the submit function defined in subscribe-block.html is not recognized.
...
 submit: (data) => this._subscribeAction(data),
...

subscribe-dialog.html:197 Uncaught TypeError: this.data.submit is not a function
    at HTMLElement._subscribe (subscribe-dialog.html:197)
    at HTMLElement.handler (template-stamp.html:92)
    at Object._fire (gestures.html:687)
    at Object.forward (gestures.html:1082)
    at Object.click (gestures.html:1045)
    at HTMLElement._handleNative (gestures.html:465)

![image](https://user-images.githubusercontent.com/776026/44679656-953c8880-aa09-11e8-860c-46d08cdcb9b7.png

**Comment by sophieH29** [comment]
Hello @lockerfish,

Does it always happen to you? Or there are specific cases when the error occurs. We haven't experienced such error, would be very helpful to have a detailed information.

**Comment by lockerfish** [comment]
I was running local. Also, developing on a chromebook not sure if firewall settings were a factor but after deploying and upgrading firebase to the paid [blaze] plan, mailchimp api works. 

So, this is what I learned. Sharing in case someone else runs into the same issue.

If you follow the install steps, everything works except login and subscribe. I believe because they both need cloud functions with outbound network connection. [not included in Firebase Spark plan]

The <DATA_CENTER_FOR_YOUR_ACCOUNT> is the last few characters after "-" in your mailchimp api. For me, it was us19.... DO NOT confuse with Firebase data center

**Comment by ozasadnyy** [comment]
Yup, you are absolutely right, you need Plaze plan for outbound network request :)
