### ISSUE TITLE
MailChimp configuration

### ISSUE THREAD

**Issue by danielgek** [gdg-x/hoverboard#501]
firebase tools don't support configs var with uppercase letters
if you try to execute the command in the docs this will come up: 
```
firebase functions:config:set mailchimpConfig.dc="..." mailchimpConfig.listid="..." mailchimpConfig.apikey="..."

Error: Invalid config name mailchimpConfig.dc, cannot use upper case.
```

i can make a pr to fix this

**Comment by sophieH29** [comment]
Hello @danielgek, you're totally right, my bad. Thank you for bringing it up and your PR is very welcome!
