### ISSUE TITLE
Order partners

### ISSUE THREAD

**Issue by venqka** [gdg-x/hoverboard#510]
Hello,

Is there a way to set a custom order for the partners? We have a few groups of partners and would like to order them.

Thanks

**Comment by ozasadnyy** [comment]
Right now there is default order by document name.
Would you like to create a PR and add order property to these documents and fetch on front-end part according to values?
![image](https://user-images.githubusercontent.com/2954281/46025784-60981b80-c0f2-11e8-96fc-5caf9ae54aa4.png)

**Comment by ozasadnyy** [comment]
Fixed in #514
