### ISSUE TITLE
sharing on social media not pulling meta info

### ISSUE THREAD

**Issue by pentium10** [gdg-x/hoverboard#518]
sharing on social media no longer works, it returns back with error

![image](https://user-images.githubusercontent.com/465691/46485337-27536000-c804-11e8-8bd5-09c2e6280e6c.png)

**Comment by abraham** [comment]
Facebook is getting a 500 error.

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fhoverboard-master.firebaseapp.com%2Fblog%2Fposts%2Fwhat-to-do-in-lviv%2F

**Comment by pentium10** [comment]
sorry I forget to read the full documentation and SEO name is misleading
you need to install rendertron to app engine, and set firebase function config and works

as described here: https://github.com/gdg-x/hoverboard/blob/master/docs/tutorials/seo.md

**Comment by gigamesh** [comment]
@pentium10 I'm stuck on step 1 "Deploy rendertron on your AppEngine" ...I can't find instructions on how to do this anywhere. Could you help? :)

**Comment by pentium10** [comment]
@gigamesh Rendertron is a separate project, follow their documentation for deploys: https://github.com/GoogleChrome/rendertron#deploying-to-google-cloud-platform
