### ISSUE TITLE
Up to date with PSK+ Lite

### ISSUE THREAD

**Issue by JosefJezek** [gdg-x/hoverboard#52]
Could you make this template up to date with PSK+ Lite using git?

https://github.com/StartPolymer/polymer-starter-kit-plus/tree/lite#updating-from-previous-version

**Comment by ozasadnyy** [comment]
It would be really nice, but I have started Hoverboard long before PSK+ Lite exists.

**Comment by ozasadnyy** [comment]
Migrated to Polymer-CLI in #100
