### ISSUE TITLE
Link to buy tickets does not work in app drawer

### ISSUE THREAD

**Issue by cnishina** [gdg-x/hoverboard#523]
There is a `$` on `href$=[[tickets.url]]`. This can be demo'd in the https://hoverboard-master.firebaseapp.com/ website when the app-drawer is on the left. See https://github.com/gdg-x/hoverboard/blob/master/src/hoverboard-app.html#L169

Also the `tickets` object is a list. The reference to tickets.url probably does not work.

**Comment by ozasadnyy** [comment]
Fixed in eaccec290cdadd8a4d30a2bcc843b00c4c78283a
