### ISSUE TITLE
Add app to home screen not displayed

### ISSUE THREAD

**Issue by bstrandjev** [gdg-x/hoverboard#528]
I saw that when one accesses dev fest Ukraine's page on a mobile phone with the latest version of Chrome he is prompted if he wants to add the app on the home screen in a nice dialog. I liked this feature, but was not able to replicate it to hoverboard.

Can somebody help me find out what needs to be added so this happens? We already have manifest.json in the hoverboard master, so this is not the problem.

**Comment by ozasadnyy** [comment]
@bstrandjev you already have everything. Here is the script that registers SW https://github.com/gdg-x/hoverboard/blob/master/scripts/service-worker-registration.js
SW itself is generating during the build https://hoverboard-master.firebaseapp.com/service-worker.js

All we have to add is a listener to show a dialog (this was added in the recent version of chrome, so we have to update our code)
https://developers.google.com/web/fundamentals/app-install-banners/

**Comment by ozasadnyy** [comment]
Fixed in #529
