### ISSUE TITLE
Can’t figure out how to add new blog posts and fix

### ISSUE THREAD

**Issue by muldoon2007** [gdg-x/hoverboard#534]
Hi, I’m organizing a conference and would love to use hoverboard as a template. 

I am seeing that the blog posts aren’t correctly rendering markdown (for example here: https://hoverboard-master.firebaseapp.com/blog/posts/c4p/) — do you how this can be fixed, and is there any documentation on the proper process for creating new markdown blog entries?

Thanks and this is an amazing template — I hope we can use it!!

**Comment by theevilhead** [comment]
hey @muldoon2007 maybe you can give this a try http://demo.showdownjs.com/ for now

**Comment by Splaktar** [comment]
There does appear to be a lack of docs/tutorials for the blog functionality of Hoverboard.

I have been using HTML in the `content` field of the blog post object and it has been working well.

**Comment by cortinico** [comment]
Side note: For the DevFest Pisa, I switched back to using local markdown files inside the `/data/posts` folders. The `content` field is now ignored. I guess this is a way more flexible approach rather than having to store the whole markdown in a JSON field.

**Comment by cortinico** [comment]
Hey @abraham 
I'd love to PR my change to use local markdown files as we did for the DevFest Pisa 2019 website.

I just want to understand if this is the preferred solution or not.
After some chat with @ozasadnyy, the rationale behind having the markdown store inside a Firestore node was to have a WYSIWYG editor and have some sort of UI to allow editors to edit/create blogposts.

In our case, using local markdown files played really well given that we could use Github PRs to do reviews of our blogposts. Moreover having local markdown files makes easy to rollback to a previous version of the blogpost. 

If we think that the WYSIWYG editor is not going to happen in the near future, is probably better to rollback to local .md files as they're definitely easier/faster to deal with.

**Comment by abraham** [comment]
My preference would be to have a single render target that is markdown which can be sourced from either a local file or from Firestore content. I think that would either mean converting the Firestore markdown client side or having a function that listens to blog post writes and stores a converted version for display. The client side version would be less work to implement but I don't know the performance characteristics of converting markdown in JS.

**Comment by cortinico** [comment]
> The client side version would be less work to implement but I don't know the performance 
> characteristics of converting markdown in JS.

I see your point. I don't really know any performance issue that MD rendering might cause using either one or the other approach.

On the other hand we do have static pages (e.g. [/data/faq.md](/data/faq.md) and [/data/cod.md](/data/cod.md)) that use only local markdown files and blogposts that use only Firestore stored markdown.

From my point of view, this is confusing for the user (at least it was confusing for me). My two cents on local md files only :)

**Comment by abraham** [comment]
There is certainly some streamlining that can be done to the app. I would like to make it easier for new sites to get up and running and more obvious how to update everything.
