### ISSUE TITLE
Hiding Google Maps branding?

### ISSUE THREAD

**Issue by domesticmouse** [gdg-x/hoverboard#535]
If I am reading your CSS correctly, the combination of https://github.com/gdg-x/hoverboard/blob/bd10fb6a355834abe203fe9c5db881ecc917f2fb/src/elements/map-block.html#L47 and https://github.com/gdg-x/hoverboard/blob/bd10fb6a355834abe203fe9c5db881ecc917f2fb/src/elements/map-block.html#L53 will wind up with a Google Map showing without branding.

Can you please make these two the same height please? Thanks!

**Comment by ozasadnyy** [comment]
@domesticmouse yeah, sorry about that. 
Actually, I am thinking of moving from dynamic maps to static one as we only need to display a place.

**Comment by domesticmouse** [comment]
Sgtm!

**Comment by ozasadnyy** [comment]
Fixed in 81292f455d6d8b359091a8918ee85c6db56eb359
