### ISSUE TITLE
Can not promote develop changes to a project running master code

### ISSUE THREAD

**Issue by bstrandjev** [gdg-x/hoverboard#536]
My scenario is the following:
 - I have a devfest website created from a fork of Master
 - I created all needed data, but in firebase directly (i.e. I have not updated firebase default data, rather added by hand in firesotre; I think this should be the right approach to that)
 - I now want to add some new additions from the develop branch to my project. However, if I merge develop in master; do firebase deploy --only functions and try serving the results the speakers block, the speakers page and the schedule do not render

Steps to reproduce:
 - make a new project in firebase
 - deploy a fork of hoverboard master, including npm run firestore:init
 - switch the repo to develop branch, preserving the firebase configuration
 - execute firebase deploy --only functions
 - Run npm run serve

Actual result:
 - speaker block, speaker page and schedule are broken now (they do not load at all)

Expected result:
 - those sections should load ok

**Comment by bstrandjev** [comment]
What is the process that hoverboard team follows for promoting changes from dev to prod?

**Comment by ozasadnyy** [comment]
@bstrandjev it's weird as firebase function for generating speakers/schedule/sessions data should be deployed if you run `firebase deploy --only functions`.
Do you have these functions deployed?
![image](https://user-images.githubusercontent.com/2954281/48674868-e2884c00-eb59-11e8-8dec-0d1261cc101d.png)

After that you should get next nodes in your DB
![image](https://user-images.githubusercontent.com/2954281/48674881-051a6500-eb5a-11e8-93b6-a2cb7e8a0c41.png)

And finally make sure that you fetch data from these nodes: https://github.com/gdg-x/hoverboard/blob/develop/scripts/redux/actions.js#L274

**Comment by bstrandjev** [comment]
I confirm the functions were created. 

I also confirm that actions.js was defined to use the generated entities.

I, frankly, can not tell why the sections described above did not load.

Does the scenario described above work ok for you?

**Comment by ozasadnyy** [comment]
I will try tomorrow.
They should be created when you change anything in speakers/schedule/sessions node. Probably function is failing? Could you please check that?

**Comment by bstrandjev** [comment]
I do not see failures. But the problem is that I am not after any modifications - the data is already there. Can it be that we need to add logic to create such generated entities for all already existing records in firestore, before the function is added?

**Comment by ozasadnyy** [comment]
I am sure that understand your question correctly but function generates data based on your existing records. Just need to trigger it

**Comment by bstrandjev** [comment]
My current understanding is that these functions are triggered on every new record for sessions, speakers and schedule. This is why I started wondering how are the already-existing entries processed by these functions. It might be that I am wrong in my understanding. 

How am I to trigger these functions then?

**Comment by ozasadnyy** [comment]
No, the function will be triggered on each create/update/delete operation and process all nodes, no matter when it was created. The easiest way to trigger it is to update some description of any speaker or session

**Comment by bstrandjev** [comment]
Hi Oleh, I do confirm that manual edit on all these entities works on the default firebase data.
On my real example, though the generation of schedule fails (the other two succeed). Do you have any suggestion how can I debug this issue (I recognize one might say this is my personal problem, but overall the current feedback from these generations is close to zero, and this needs to be addressed)

**Comment by bstrandjev** [comment]
The flag truly did the trick, but I believe this was far from obvious thing to do. I wonder how is this whole process to be documented?
Also what about the question on release and merge to master strategy? When are these changes to be promoted to master?

**Comment by ozasadnyy** [comment]
New users will not feel any difference but I am with you that it should be documented somehow.
About the release, probably this week. As you see we have to document it properly and describe a migration path.

**Comment by ozasadnyy** [comment]
Now there will be an error in Firebase functions console if there is no schedule config set https://github.com/gdg-x/hoverboard/commit/b58600e41835b174ee0395f71eb899e17b5e7671
