### ISSUE TITLE
Deployment don't update site data

### ISSUE THREAD

**Issue by Nuruddinjr** [gdg-x/hoverboard#537]
When I build and deploy new website, I don't get `new version available` toast, instead it gives following error on console
```
Uncaught (in promise) TypeError: Failed to fetch
service-worker-registration.js:32 Uncaught Error: The installing service worker became redundant.
    at ServiceWorker.installingWorker.onstatechange (service-worker-registration.js:32)
installingWorker.onstatechange @ service-worker-registration.js:32 
```

But website content is still same. 

What might be the problem?

I can go to application and clear cache, or open incognito to see the changes, but how about our users? how do they see the changes?

**Comment by ozasadnyy** [comment]
@Nuruddinjr fixed in develop branch. Please fetch changes from there and let us know if it works for you

**Comment by Nuruddinjr** [comment]
@ozasadnyy seems like it fixes the problem.

**Comment by muldoon2007** [comment]
@ozasadnyy I have run into this as well. Is this the commit that we need to incorporate? https://github.com/gdg-x/hoverboard/commit/f4689d37b3c4a5e298c9008b616502caa9b06a38#diff-dfd70b60f8469fdc3ee3b3935d64d130

**Comment by ozasadnyy** [comment]
@muldoon2007 yes it is :)
