### ISSUE TITLE
DEPRECATED: HTML Imports

### ISSUE THREAD

**Issue by gangadharjannu** [gdg-x/hoverboard#541]
While running the application in chrome I could see the warning `[Deprecation] HTML Imports is deprecated and will be removed in M73, around March 2019. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 for more details.`

If this is going to be deprecated what is the future of this application?

**Comment by jcf120** [comment]
I'd also very much like to know, please! Does hoverboard have any kind of fallback for when html imports no longer work? The planned Chrome removal date coincides with our conference, so the timing is rather unfortunate!

**Comment by abraham** [comment]
Yes, if you site works now in Firefox it should continue to in Chrome after they remove HTML Imports support. It might be a little slower as it will have to use the polyfill.

**Comment by jcf120** [comment]
Thanks!

**Comment by felixzapata** [comment]
hi, according with this article [Web Components v0 deprecations](https://www.polymer-project.org/blog/2018-10-02-webcomponents-v0-deprecations):

> If you have existing sites using Polymer 1.x or 2.x, you'll need to make sure you're loading the polyfills, and test your sites to make sure they'll continue to work after the native features are removed.

> If you're using the polyfills, your sites should continue to function on Chrome as they do on other browsers.

> The features being deprecated were only shipped in Chrome and other Chromium-based browsers, such as Opera. Most sites using Polymer 1.x or 2.x should already be using polyfills for the required features.

**Comment by abraham** [comment]
I've started the process of upgrading to Polymer 3 with #578. This will remove the usage of HTML Imports.
