### ISSUE TITLE
Any experiments / success stories about building the app for IE11?

### ISSUE THREAD

**Issue by webmaxru** [gdg-x/hoverboard#548]
Hello!
First, I know that officially "❌ IE and Opera Mini aren't supported". But still, it would be cool to have Hoverboard v2 running in IE11. Maybe someone from the dev community succeeded with customizing the build flow to polyfill / transpile the needed parts?

I did a quick try to add Babel to build pipeline `.pipe(gulpif(/\.js$/, babel({presets: ['@babel/env'],})))` with `"targets": {"ie":"11"}`in Babel config, and `"js": {"compile": true}` in Polymer config. Build succeeds but I get `Uncaught ReferenceError: ReduxMixin is not defined` in the console.

Any ideas which direction to move from that point?

**Comment by abraham** [comment]
I feel like this should be doable but I've not attempted it myself. [PWA Starter Kit](https://pwa-starter-kit.polymer-project.org/) supports IE11 so maybe a good direction for Hoverboard is to work towards a similar build pipeline.

**Comment by abraham** [comment]
The project is now using OpenWC to build. It should be possible to use the `legacyBuild` config to target IE11.

https://open-wc.org/building/building-rollup.html#supporting-older-browsers
