### ISSUE TITLE
SEO canonical link meta tag

### ISSUE THREAD

**Issue by jcf120** [gdg-x/hoverboard#556]
Currently the site has just a single canonical meta tag, which is for the site root.
```
<link rel="canonical" href="{$ url $}">
```
Isn't this massively hurting SEO? I was under the impression that if all pages uses the same canonical link, only the first will be indexed.

**Comment by ozasadnyy** [comment]
Yeah, you are right, it should be changed. Would you like to create a PR with the fix?

**Comment by jcf120** [comment]
Ok sure, I've just opened a small PR.
