### ISSUE TITLE
Can't edit local files

### ISSUE THREAD

**Issue by Nuruddinjr** [gdg-x/hoverboard#56]
When I edit sitedata.js i cant see any updates in my local website

**Comment by ozasadnyy** [comment]
Hello, @Nuruddinjr . Try to delete `.tmp` and `dist` folders and restart server

**Comment by Nuruddinjr** [comment]
thank you ,so for every change , should i repeat this step ?

**Comment by ozasadnyy** [comment]
Currently yes, I am going to fix that in next release.

**Comment by Nuruddinjr** [comment]
Thank you.

**Comment by Nuruddinjr** [comment]
sorry @ozasadnyy how can I delete video , add another photo

**Comment by ozasadnyy** [comment]
@Nuruddinjr look in this files: https://github.com/gdg-x/hoverboard/tree/master/app/metadata

**Comment by Nuruddinjr** [comment]
i can delete video , then how to add photo, 
sorry for offtop and dumb questions 😬

**Comment by ozasadnyy** [comment]
@Nuruddinjr are you talking about hero-section?

**Comment by Nuruddinjr** [comment]
Why this error is caused when i change schedule, speakers?
app-data.js:102 Uncaught TypeError: Cannot read property '1001' of null

**Comment by ozasadnyy** [comment]
It's id of an session/speaker. You should missed to define some.

**Comment by Nuruddinjr** [comment]
Is it okay if i write here all of things that i cant understand

**Comment by ozasadnyy** [comment]
@Nuruddinjr not really. Github issues more for bugs and improvements.

**Comment by Nuruddinjr** [comment]
okay I will delete later , can i get your email or any way of comunication?

**Comment by Splaktar** [comment]
I'm seeing this too. Modifying anything in `elements/` doesn't seem to get picked up when doing `gulp serve` for local development. I have to do a bunch of extra steps to get it to load and be able to test it. It's not a good experience.

**Comment by ozasadnyy** [comment]
@Splaktar version in a master will be dropped soon. Please use from develop branch instead

**Comment by Splaktar** [comment]
OK, I'll give it a shot when I have a few hours to try upgrading.

**Comment by ozasadnyy** [comment]
Migrated to Polymer-CLI in #100 . After files updated you have to reload page manually.
