### ISSUE TITLE
Make speakers and videos data generation independent from schedule on fetch 

### ISSUE THREAD

**Issue by ozasadnyy** [gdg-x/hoverboard#58]

**Comment by tasomaniac** [comment]
But schedule needs speakers right? Are you planning to make all of them async?

**Comment by ozasadnyy** [comment]
Schedule needs. But for now, we can't show just speakers and videos without parsing `sessions.json` and `schedule.json`

**Comment by tasomaniac** [comment]
I see. This can definitely be improved. :+1:

**Comment by ozasadnyy** [comment]
Fixed in #100
