### ISSUE TITLE
Feedback/Rating for sessions/speakers in hoverboard v2

### ISSUE THREAD

**Issue by radi-cho** [gdg-x/hoverboard#615]
A module for rating/commenting the sessions/speakers.

## Description
I have already built a simple feedback module: https://github.com/radi-cho/hoverboard/commit/c7f0eab78b9b03ea0ec1214a521d501061905362

The user can rate a session/speaker with 1-5 stars and leave an optional comment. The rating is connected with Firebase Auth so only authenticated users can submit feedback. The data is recorded in Firestore: `/{sessionsOrSpeakers}/{sessionId}/feedback/{userId}`. This data structure allows the user to easily edit/update/delete existing feedback. Once a session/speaker dialog is opened, a redux action checks for previously submitted rating/comment from the user and displays it (if it exists). If the user hasn't signed in it will be prompted via snackbar. After sign out the feedback state in redux is reset.

## Code
- https://github.com/radi-cho/hoverboard - The basic functionality described above is already implemented and working;
- https://github.com/radi-cho/star-rating - I've forked and extended the functionality of the [greenyouse/star-rating](https://github.com/greenyouse/star-rating) component;

## Pull Request - #617 
~~If the idea is well accepted by the community I'll open a PR. Any advice on the design, things to add/change/remove and code refactoring recommendations are greatly appreciated.~~

**Comment by abraham** [comment]
I think this would be a great addition. I haven't looked through the UX yet but will try to do that soon.

**Comment by abraham** [comment]
Implemented in #690
