### ISSUE TITLE
Doesn't load on any other browser but Chrome

### ISSUE THREAD

**Issue by tomasdfen** [gdg-x/hoverboard#620]
Hi, once I've deployed with no errors, trying to open my web page with any browser thats not Chrome (desktop or mobile), it just load a blank page with the title in the middle and nothing else.

the page: https://devfest-sev19.firebaseapp.com/

**Comment by abraham** [comment]
There are several JavaScript files that are failing. For example `https://devfest-sev19.firebaseapp.com/node_modules/firebase/firebase-app.js`. They are returning HTML instead which suggests that the build or deploy didn't work correctly. Try installing dependencies and deploying again.

```
$ npm install
$ npm run deploy:prod
```

**Comment by adben** [comment]
Any pointers on this issue? very hard to trace when stopped working on non-chrome browsers!

**Comment by cortinico** [comment]
> Any pointers on this issue? very hard to trace when stopped working on non-chrome browsers!

Hey @adben Can you link a deployed instance of Hoverboard that is not working on other browser? I'd love to investigate

**Comment by abraham** [comment]
Please do open a new issue with a specific URL and specific browser versions you're having issues with. This particular site seems to be working now.
