### ISSUE TITLE
Signing out on "my schedule" path doesn't change

### ISSUE THREAD

**Issue by abraham** [gdg-x/hoverboard#627]
1 Sign in and go to "my schedule" https://hoverboard-master.firebaseapp.com/schedule/my-schedule
2 Sign out
3 URL is still `/schedule/my-schedule`

Tab's are weird and schedule page is still displayed. User should get redirected to `/schedule`.

**Comment by giulianovarriale** [comment]
Can I work on this one?

**Comment by abraham** [comment]
Please do!

**Comment by abraham** [comment]
#2141 would be better.
