### ISSUE TITLE
Update tag design

### ISSUE THREAD

**Issue by abraham** [gdg-x/hoverboard#628]
Session tag/complexity design should be updated to match current MD chip design.

Old:
![Screenshot from 2019-08-18 11-22-51](https://user-images.githubusercontent.com/3341/63227313-929eea00-c1aa-11e9-8a7d-8bf017518ebd.png)

New: 
https://material.io/design/components/chips.html

**Comment by cortinico** [comment]
Probably blocked by #616 ?

**Comment by abraham** [comment]
Those would make it easier to implement but I wouldn't say it's blocked by it. It could be implemented with the non web component version of MDC.
