### ISSUE TITLE
Images are not shown in production

### ISSUE THREAD

**Issue by Nuruddinjr** [gdg-x/hoverboard#63]
images are not shown on firebase
`https://iutx.firebaseapp.com`

**Comment by ozasadnyy** [comment]
@Nuruddinjr please, provide link to your repository

**Comment by Nuruddinjr** [comment]
https://github.com/Nuruddinjr/io

**Comment by Nuruddinjr** [comment]
Images are not shown only in production

**Comment by Nuruddinjr** [comment]
Sorry, any updates on this issue?

**Comment by Nuruddinjr** [comment]
When extension is in Capital letters, firebase doesn't get those photos.
