### ISSUE TITLE
Clicking on speaker from session details should navigate to speaker details page

### ISSUE THREAD

**Issue by abraham** [gdg-x/hoverboard#632]
1. Go to https://hoverboard-master.firebaseapp.com/schedule/2016-09-09?sessionId=103
1. Click on speaker
1. URL should be `https://hoverboard-master.firebaseapp.com/speakers/yonatan_levin`

**Comment by beitanssaatans** [comment]
At the moment struggling with this one as well. 
For now I think that speakers-seassions-map function not working properly, and that is why when I click on speaker, it shos undefiened speakers details, and schedule is empty as well as sessions. 
It gets data from the database but does not map them so nothing is shown in the end.

**Comment by abraham** [comment]
That's a different problem. Please open a new issue.

**Comment by abraham** [comment]
Fixed in #2099
