### ISSUE TITLE
can't edit default speakers to use local speaker

### ISSUE THREAD

**Issue by umeklinks** [gdg-x/hoverboard#635]
I'm having issues trying to add my own speakers in the speakers session from firebase. I tried deleting some speakers data from my firebase firestore and also that of `default-firebase-data.json` but on restarting the web app it still carries the default data, no changes made. 
Please what's the best approach to add my own speakers? I have few days left to launch the web app.

**Comment by umeklinks** [comment]
oh... I've found where it is. It's located in the `generatedSpeakers`. Adding or editing from there makes changes on your speakers session.

**Comment by abraham** [comment]
You should not edit any of the `generated*` tables. Those should be generated by the Firebase functions when the `speaker`, `sessions`, or `schedule` collections are edited. If changing those collections doesn't change what's displayed, check your Functions are deployed and their logs for any errors.
