### ISSUE TITLE
Partners and Team not showing when deployed

### ISSUE THREAD

**Issue by umeklinks** [gdg-x/hoverboard#647]
I'm having issues when deployed the web app to Firebase. The partners logo and team members are not showing when I deployed to firebase but the Ticket is showing from contect from the firestore.

Meanwhile when I run it locally using `npm start` everything works perfectly.

I need help. I think I'm not getting somethings write.
Attached are the screenshots.

![partner](https://user-images.githubusercontent.com/13150442/64079304-e8f94600-ccdd-11e9-9680-7b44d752e201.png)
![team](https://user-images.githubusercontent.com/13150442/64079307-f9a9bc00-ccdd-11e9-82c4-e02e749efa68.png)
![ticket](https://user-images.githubusercontent.com/13150442/64079309-00d0ca00-ccde-11e9-99e2-7f26e8aad590.png)

**Comment by cortinico** [comment]
Hey @umeklinks 
Can you provide a link to your repository and/or to your website?

Data for partners and teams is fetched for the Firestore. If they're not leaded the problem could be either:

a) You haven't properly configured hoverboard to connect with you Firebase app (see [config/development.json](config/development.json) and [config/production.json](config/production.json)).

b) You don't have data for sponsors and team in Firestore.

Given that tickets are loaded properly, I assume you might have problem with the data. Have you populated your Firestare with the [docs/default-firebase-data.json](docs/default-firebase-data.json) file?

**Comment by umeklinks** [comment]
Hey @cortinico thanks for your reply.

Here's my repository link [https://github.com/umeklinks/gdgbonny-devfest](url) and here's the link to the firebase deployed web app [https://gdg-devfest-bonny.firebaseapp.com/](url)

The firestore has partners in place of sponsors and I have team as well.

Please go through my repo for errors.

As for the [docs/default-firebase-data.json](url) I It has the default data.

Attached is a screenshot of my database.
![db](https://user-images.githubusercontent.com/13150442/64081876-ece99000-ccfe-11e9-8964-c2f58f653ddf.png)

**Comment by cortinico** [comment]
Hey @umeklinks 
So you definitely have some configuration problems:
https://github.com/umeklinks/gdgbonny-devfest/blob/231b388c02a57bc68a8cc18453dbdc8da89f12f0/config/production.json#L3

`url` should be the public URL of your website: https://gdg-devfest-bonny.firebaseapp.com/

Can you fix this configuration (in both development and production) and re-deploy please?

**Comment by abraham** [comment]
Another issues is you are loading an additional version of the Firebase SDK in `index.html`. They are already being loaded https://github.com/umeklinks/gdgbonny-devfest/blob/231b388c02a57bc68a8cc18453dbdc8da89f12f0/index.html#L96:L101

**Comment by abraham** [comment]
Make sure that each document in the items subcollection has a `order` key with a number value. The current DB query will only return results that have an `order`. https://github.com/umeklinks/gdgbonny-devfest/blob/2fda4c8b269bf09edec38d381d989ee53091cb25/scripts/redux/actions.js#L134

**Comment by abraham** [comment]
If you have any further issues please let us know.
