### ISSUE TITLE
IE 11 Polyfills not working?

### ISSUE THREAD

**Issue by RIsoldier** [gdg-x/hoverboard#66]
The [suggested method](https://www.polymer-project.org/1.0/docs/browsers) of checking if web components are supported in your browser is [already implemented](https://github.com/gdg-x/hoverboard/blob/master/app/scripts/app.js), but it doesnt seem to work. I get blank pages.

**Comment by MrCsabaToth** [comment]
Console log:

    DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
    hoverboard.firebaseapp.com
    HTML1300: Navigation occurred.
    hoverboard.firebaseapp.com
    SCRIPT1003: Expected ':'
    util.js (270,21)
    SCRIPT5007: Unable to get property 'createDeferred' of undefined or null reference
    analytics.js (1,1242)
    SCRIPT1003: Expected ':'
    elements.js (26,3)
    SCRIPT1003: Expected ':'
    service-worker-registration.js (85,13)
    SCRIPT5007: Unable to get property 'getChromeVersion' of undefined or null reference
    bootstrap.js (1,575)
    SCRIPT5007: Unable to get property 'init' of undefined or null reference
    bootstrap.js (1,1118)
    SCRIPT5007: Unable to set property 'Tickets' of undefined or null reference
    javascript;charset=utf-8,!function(){&quot;use strict&quot;;Polymer({is:&quot;tickets-block&quot;,behaviors:[HOVERBOARD.LocalizeBehavior],ready:function(){HOVERBOARD.Elements.Tickets=this},_trackBuyClick:function(t){HOVERBOARD.Analytics.trackEvent(&quot;ticket&quot;,&quot;buy_click&quot;,t.currentTarget.href)}})}();
//# sourceURL=https://hoverboard.firebaseapp.com/src/hoverboard-app.html-114.js
 (1,111)

**Comment by MrCsabaToth** [comment]
The first error (`Expected ':'`) suggests to me that this is rather about ES6 support or similar. So maybe something needs to be changed in the build pipeline. I'm hosting now an `unbundled` build of my own fork, I don't know what does the public demo app uses, but I'll try the `bundled`.

**Comment by MrCsabaToth** [comment]
Bundled or unbundled, same thing happens.
