### ISSUE TITLE
Using Product Sans font with restricted license for the headers

### ISSUE THREAD

**Issue by webmaxru** [gdg-x/hoverboard#682]
Hello!
I explored a bit about the permission to use Product Sans font used for the headers:
https://github.com/gdg-x/hoverboard/blob/master/src/elements/shared-styles.html#L85

It seems like it's a proprietary Google's font for internal usage. It's not listed at resource Google Fonts https://fonts.google.com/?query=product
Also, the link to https://fonts.google.com/license/googlerestricted saying "Google offers many fonts under open source licenses. This is not one of them. Please see fonts.google.com for options you can use." is included in CSS file https://fonts.googleapis.com/css?family=Product+Sans:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i

Discussion on Quora: https://www.quora.com/Where-can-I-download-the-Google-Product-Sans-font

Should we consider changing it to something else to avoid potential licensing issues?

**Comment by abraham** [comment]
Sounds good to me. I would favor switching to [system fonts](https://markdotto.com/2018/02/07/github-system-fonts/).

**Comment by webmaxru** [comment]
The sent PR covers only removing explicitly set font-family for the titles - to quickfix the licensing issue. Switching the whole app to system fonts like in the mentioned GitHub is a good idea but more investigation and testing needed :)
