### ISSUE TITLE
Error npm install on windows

### ISSUE THREAD

**Issue by shnathoskhan** [gdg-x/hoverboard#689]
Pls, refer my log file.

PFA.

https://docs.google.com/document/d/1uLc9VaTE3i5hDCyQqbhD6P0Hp8AJGG3v5FTYfP9qfwc/edit?usp=sharing

node-pre-gyp WARN

**Comment by abraham** [comment]
I was able to install and run on Windows 10 with PowerShell and with WSL with node 10. It looks like you're using node 13. Can you try with node 10 and see if that works. If node 10 doesn't work please include details about your Windows version, PowerShell/WLS versions, and as much about the environment as you can.

**Comment by shnathoskhan** [comment]
> I was able to install and run on Windows 10 with PowerShell and with WSL with node 10. It looks like you're using node 13. Can you try with node 10 and see if that works. If node 10 doesn't work please include details about your Windows version, PowerShell/WLS versions, and as much about the environment as you can.

@abraham Thanks for reply.

i installed Node 10 and i tried npm install but i got same error.

PowerShell version:
Version
-------
5.1.18362.145

Windows Version:
Version 1903 (OS Build 18362.476)

**Comment by abraham** [comment]
Can you attach the node 10 logs please. 

Are you trying to use the latest version of the master branch? If not what version of the app are you trying to use?

How are you installing node? With the official windows installer? Some other way?

**Comment by shnathoskhan** [comment]
> Can you attach the node 10 logs please.
> 
> Are you trying to use the latest version of the master branch? If not what version of the app are you trying to use?
> 
> How are you installing node? With the official windows installer? Some other way?

Yes i tried master branch. and sure i used official windows installer https://nodejs.org/dist/v10.0.0/ .

i attached my log.
https://drive.google.com/file/d/1BehLzv4dXi92QMCq1PHRi-YmYiv2zB52/view

**Comment by abraham** [comment]
If you used v10.0.0 that's pretty old. Try the 10.18 version https://nodejs.org/dist/latest-v10.x/

**Comment by abraham** [comment]
If you still have issues please let me know.
