### ISSUE TITLE
Speaker and Session Model

### ISSUE THREAD

**Issue by atharvaunde59** [gdg-x/hoverboard#699]
After clicking the speaker's name or on clicking the session card it is not opening the popup to show details. Is it broken or needs to configure manually?
On clicking the speaker it changes the URL with the speaker name but doesn't opens the dialog...

PS: It opens but it takes too much time to open

**Comment by abraham** [comment]
Thanks for the report.

**Comment by atharvaunde59** [comment]
Thanks a lot!
Working like charm now!!!
