### ISSUE TITLE
Speaker expertise filters not working in FF

### ISSUE THREAD

**Issue by twhetzel** [gdg-x/hoverboard#7]
On the page http://devfest.gdg.org.ua/#!/speakers, the filters to indicate the speakers expertise are not working in Firefox (tested version 40.0.3). The filters are working in Chrome. Unable to test in Safari due to a formatting issue on this page.

**Comment by ozasadnyy** [comment]
Filters were removed in the new version

**Comment by tasomaniac** [comment]
Are they going to come back? What was the reason for the removal?

**Comment by ozasadnyy** [comment]
You can filter session instead that makes more sense

**Comment by tasomaniac** [comment]
Yeah, that makes sense.
