### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by giantthinker** [gdg-x/hoverboard#70]
Hello, I want to use project hoverboard to make the GDG website of my community but I fail to install some of the required files in my computer to enable me use and edit it. Preview here  [image](https://postimg.org/image/7xjrdsnht/ )

**Comment by ozasadnyy** [comment]
Hello @giantthinker , try to run commands separately:
`npm install`, `npm install -g bower gulp` and `bower install`

**Comment by giantthinker** [comment]
Thanks @ozasadnyy but all I get is error even when I do that in the folder where I cloned and downloaded the file in.

**Comment by ozasadnyy** [comment]
Event first command?

**Comment by giantthinker** [comment]
Thank you @ozasadnyy I skipped this "cd hoverboard && npm install && bower install".

**Comment by giantthinker** [comment]
Hello, this is another problem I am facing.
![gulp issue](https://cloud.githubusercontent.com/assets/17084652/16825373/2a276d12-496c-11e6-8ce8-fe46bf1d8454.PNG) . The app cannot be initialiazed.

**Comment by ozasadnyy** [comment]
@giantthinker you don't need to init gulp because it's already initialized.

**Comment by giantthinker** [comment]
Okay now that I have downloaded the files and can edit it the way I want, please how will I make a domain name from it or how can I make it go online. I am sorry if this question sounds stupid it is because I have not mastered it yet.

**Comment by ozasadnyy** [comment]
I suggest to use Firebase for hosting. Read the [documnentation ](https://firebase.google.com/docs/hosting/)for details.
