### ISSUE TITLE
Speakers and Team Offline Access

### ISSUE THREAD

**Issue by atharvaunde59** [gdg-x/hoverboard#701]
Adding support for Firestore Offline Caching of Documents and collections 
https://cloud.google.com/firestore/docs/manage-data/enable-offline

**Comment by cortinico** [comment]
Offline caching is already enabled in hoverboard:
https://github.com/gdg-x/hoverboard/blob/adc048936f3fc518c0dd03efdaa8c03622dc6d2f/index.html#L114-L118
