### ISSUE TITLE
Problems with eslint 

### ISSUE THREAD

**Issue by benju69** [gdg-x/hoverboard#705]
Hi, I just updated my fork to the last version, resolved conflicts and not merged yet.
When I build I have lint errors, How I can fix them or disable the eslint step ?

**Comment by cortinico** [comment]
> When I build I have lint errors, How I can fix them or disable the eslint step ?

Can you please post the output of eslint?

**Comment by abraham** [comment]
The latest version has been updated with prettier. It will automatically format your code with `npm run format:fix` so linting issues should be much less common.

**Comment by benju69** [comment]
ok I will re test :)
