### ISSUE TITLE
Google Maps API key warnings

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hoverboard#83]
The google-map component has an [apiKey](https://elements.polymer-project.org/elements/google-map#property-apiKey) property which isn't being set. There should be a spot in the config for setting this and then it should be injected in `map-block.html`.

```
No Google Maps API Key or Client ID specified. See https://developers.google.com/maps/documentation/javascript/get-api-key for instructions to get started with a key or client id.
```

```
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
```

Currently:
```
<google-map zoom="{$ location.pointer.zoom $}" latitude="{$ location.mapCenter.latitude $}"
                longitude="{$ location.mapCenter.longitude $}" styles="[[options]]" 
                disable-zoom disable-default-ui>
      ...
</google-map>
```

Should be something like:
```
<google-map zoom="{$ location.pointer.zoom $}" latitude="{$ location.mapCenter.latitude $}"
                longitude="{$ location.mapCenter.longitude $}" styles="[[options]]" 
                disable-zoom disable-default-ui api-key="{$ apiKey $}">
      ...
</google-map>
```

**Comment by Splaktar** [comment]
This PR contains a fix for this: https://github.com/SunCoastGDG/DevFestFloridaSite/pull/1/commits/93d8b5e2e07637d5cf055bde779ac9fcd06e81e5

Would a PR be desired for this here?

**Comment by ozasadnyy** [comment]
Already have it in a new version: https://github.com/gdg-x/hoverboard/blob/develop/src/elements/map-block.html#L120
Thanks!
