### ISSUE TITLE
cascaded-animation.html:78 Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hoverboard#84]
This is happening all of the time since we modified the `speakers.json` and `sessions.json`. We've tried to make sure that everything is setup right, but it keeps throwing. This causes the Blog and Speakers pages to not load.

How can we fix this quickly so that we can get our site online? 
Can you just disable some of these animations or something?

```
cascaded-animation.html:78 Uncaught TypeError: Cannot read property '0' of undefined
fire @ polymer.html:1287
```

**Comment by Splaktar** [comment]
Solved in https://github.com/SunCoastGDG/DevFestFloridaSite/issues/4. Bower resolutions should override to 1.3.x to make sure that no one chooses 1.5.x which is required by iron-ajax and a number of other components. 1.5.x does not work with the animations in hoverboard.

**Comment by ozasadnyy** [comment]
@Splaktar could you check if it is reproducible after v.1.0.0?

**Comment by tasomaniac** [comment]
Hmmm, I always choose `hoverboard` in the list when there is dependency conflict.
