### ISSUE TITLE
develop: README references to app-drawer-template instead of hoverboard

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hoverboard#85]
Title: Polymer App Toolbox - Drawer Template
Initialization step: `polymer init app-drawer-template`

Running this init step wipes out a lot of hoverboard code as the app already seems to be initialized. This probably needs to be removed from the readme?

Should the README include running `bower install`?
It looks like npm and `node_modules` is gone now in `develop`?

I think that these instructions need to be updated to be more specific to hoverboard?

**Comment by ozasadnyy** [comment]
@Splaktar I haven't touched README file yet. I am going to write docs before the release .

**Comment by ozasadnyy** [comment]
Fixed for quick dive-in the project.

**Comment by Splaktar** [comment]
Thanks!

Fixed in https://github.com/gdg-x/hoverboard/commit/d42df10eb82f4ab2867f31efd25363737bd74c27
