### ISSUE TITLE
FIrebase don't make generatedSpeakers or generatedSchedule

### ISSUE THREAD

**Issue by benju69** [gdg-x/hoverboard#856]
Firebase don't want to generate speakers or schedule, how I can debug this ?

**Comment by abraham** [comment]
Check to make sure the functions have been deployed to Firebase in the console: https://console.firebase.google.com/

![Screen Shot 2020-04-07 at 08 05 17](https://user-images.githubusercontent.com/3341/78672632-8afd9400-78a6-11ea-9118-88f71482c27f.png)

If they have been deployed check the logs for any errors

![Screen Shot 2020-04-07 at 08 05 42](https://user-images.githubusercontent.com/3341/78672703-a072be00-78a6-11ea-82d6-159a8c57ac3a.png)

**Comment by benju69** [comment]
ah yes thank you so much, logs saved me :)
