### ISSUE TITLE
Code of Conduct link goes no where

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hoverboard#88]
It looks like the routing is broken for the CoC link at the bottom of the home page. This is in `master`.

Note that https://hoverboard.firebaseapp.com/code-of-conduct doesn't open the CoC page.

**Comment by ozasadnyy** [comment]
https://hoverboard.firebaseapp.com --> master
https://hoverboard-dev.firebaseapp.com --> develop

**Comment by Splaktar** [comment]
@ozasadnyy not sure what your response was supposed to mean. This seems to be a problem in `master` which is the version that people are using (`develop` wasn't ready to use the 2-3 times that we tried it).
