### ISSUE TITLE
Make `gulp deploy` work with two-factors authentication at github

### ISSUE THREAD

**Issue by friedger** [gdg-x/hoverboard#9]
Users that have 2FA enabled at github are not able to deploy. They are asked for username/password which fails.

**Comment by ozasadnyy** [comment]
I have created [issue](https://github.com/shinnn/gulp-gh-pages/issues/72) on a the plugin page.

**Comment by tasomaniac** [comment]
What is the workaround for this currently? What are you guys doing besides disabling 2FA

**Comment by phawxby** [comment]
Personal access tokens!

	return gulp
		.src('./build/**/*')
    	.pipe(ghPages({
			"remoteUrl" : "https://phawxby:[]@github.com/xeroxinteractive/guide.git"
		}));

**Comment by tasomaniac** [comment]
New version does not even use github pages. For the previous version, the following can be added with ssh keys to work with 2FA enabled accounts. 

```
gulp.task('gh-pages', function() {
  return gulp.src('./dist/**/*')
    .pipe(ghPages({
      "remoteUrl" : "git@github.com:gdgistanbul/devfest15.git"
    }));
});
```
