### ISSUE TITLE
Opening subroute before cache results in a "Not Found" error

### ISSUE THREAD

**Issue by gregoriopalama** [gdg-x/hoverboard#924]
Replicating the issue is pretty easy. 
Opening a subpage through incognito mode (for example, https://BASEURL/team), the site gives out a "Not Found" error.

The under-the-hood behaviour is this one:
- the redirection for everything that is not matched redirects everything to the prerender function
- the prerender function performs res.sendFile(path.join(__dirname + '/index.html'));
- the result for this is an error for the function. In the Firebase console, I can see this error:
Error: ENOENT: no such file or directory, stat '/workspace/dist/index.html'

I'm currently trying to solve this, so I might come back with a solution soon.

**Comment by cortinico** [comment]
That's weird as I'm not able to reproduce on the DevFest Pisa website. Try to open incognito this: https://devfest.gdgpisa.it/team

**Comment by abraham** [comment]
Try building the web app and then deploying the functions again. I suspect the index.html file wasn't correctly copied to the functions deploy.

**Comment by gregoriopalama** [comment]
The issue is already solved with this commit: https://github.com/gdg-x/hoverboard/commit/041742424db5060c7c9a04f58799f9b9aae0acd3#diff-325fcb164a87c4ba23a1f0dab1460a1e.

Sorry, didn't notice it before opening this issue. I'm going to close it.
