### ISSUE TITLE
Disable video sections when we don't have video

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hoverboard#95]
When the video related configs are removed, hide the video related parts in the home page. 

It is great to have video call to action etc, but not many chapters have that kind of video from last year. 

When we configure the site, if we just delete the video related parts from `config.json`, they should disappear. 

Here are the candidates I found. 
- `callToAction`
- `videosSessionsUrl`
- `video` in `home` - `headerSettings`

**Comment by ozasadnyy** [comment]
@tasomaniac, do you mean in a header?

**Comment by tasomaniac** [comment]
There are couple of sections where we have video. 
Play List section and Call To Action section can be removed by their own. 
My first problem was the video in the header.

**Comment by tasomaniac** [comment]
When I delete `videosSessionsUrl` playlist for example from the config, `VIEW ALL VIDEOS` button stay and when I press it, it opens `http://localhost:8080/undefined`

**Comment by ozasadnyy** [comment]
You have to delete that block manually in `home-page.html`

**Comment by htchien** [comment]
We at GDG Taipei  also have this issue (along with the Photos section). If they both can be disabled when no photos / videos supplied then it would be great!

**Comment by ozasadnyy** [comment]
Doesn't applicable to the current version of Hoverboard
