### ISSUE TITLE
Multiple primary buttons in the header

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hoverboard#96]
In the main header, we have "Buy Ticket" button. 
I think chapters may have multiple buttons there. They can be defined in `config.json` with an array just like `pages` or `navigation`.

The button title, link will be controlled from that array.

**Comment by ozasadnyy** [comment]
Good point! We will see how to do it in a proper way.

**Comment by tasomaniac** [comment]
I guess this is not hard. I opened this for people who wants to contribute. This can be grabbed easily, right?

**Comment by ozasadnyy** [comment]
I want to clear a code before asking someone to contribute. But in general it's pretty easy for web developers

**Comment by MrCsabaToth** [comment]
Right now I went quick & dirty with my fork and just copy pasted for a "Buy T-shirt" button. The array what @tasomaniac proposes could be used at least 3 different places: the tickets element, the drawer element and the header. I modified all 3 places, I have now two buttons.

**Comment by ozasadnyy** [comment]
You can do it, but manually. We don't generate them dynamically. 
Also, it is a bad idea to have several CTAs in the header
