### ISSUE TITLE
Add social share buttons to the blog posts

### ISSUE THREAD

**Issue by zasadnyy** [gdg-x/hoverboard#97]
Blog posts are missing social share buttons, what about adding them here http://take.ms/mgS7G

**Comment by ozasadnyy** [comment]
@zasadnyy date is above a post title

**Comment by zasadnyy** [comment]
I know, maybe we can move it there, coz only buttons look a bit empty

**Comment by ozasadnyy** [comment]
Social icons should be on a bottom of a post or as floating button in a header (just like in a session dialog).

**Comment by zasadnyy** [comment]
Also a good idea

**Comment by ozasadnyy** [comment]
Added.
![share-buttons](https://cloud.githubusercontent.com/assets/2954281/18028471/0e4dc862-6c89-11e6-8432-82a2041cea09.png)
